import { defineExample, definePage, lazyPage } from './registry';

export const EXAMPLE_ENTRIES = [
  defineExample({
    id: 'paging-zero',
    pageId: 'example-paging-async',
    anchor: 'paging-zero',
    title: { en: 'Fetch every page from page 0', vi: 'Lấy mọi trang từ trang 0' },
    summary: {
      en: 'Exhaust a zero-based HTTP endpoint with cancellation and bounded progress.',
      vi: 'Lấy hết endpoint HTTP zero-based với hủy yêu cầu và giới hạn tiến trình.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/paging-zero.example.ts?raw')).default,
    relatedSymbols: ['fetchAllByPaging', 'FetchAllByPagingOptions'],
  }),
  defineExample({
    id: 'paging-one-based',
    pageId: 'example-paging-async',
    anchor: 'paging-one-based',
    title: { en: 'Adapt a one-based transport', vi: 'Chuyển đổi transport one-based' },
    summary: {
      en: 'Keep application paging zero-based and add one only inside the transport callback.',
      vi: 'Giữ phân trang ứng dụng zero-based và chỉ cộng một trong callback transport.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/paging-one-based.example.ts?raw')).default,
    relatedSymbols: ['fetchAllByPaging'],
  }),
  defineExample({
    id: 'async-rxjs',
    pageId: 'example-paging-async',
    anchor: 'async-rxjs',
    title: { en: 'Resolve values, promises, and subscribables', vi: 'Resolve giá trị, promise và subscribable' },
    summary: {
      en: 'Use the dependency-free structural contract that is also compatible with an application-owned RxJS Observable.',
      vi: 'Dùng contract cấu trúc không phụ thuộc runtime, đồng thời tương thích Observable RxJS do ứng dụng sở hữu.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/async-rxjs.example.ts?raw')).default,
    relatedSymbols: ['MaybeAsync', 'SubscribableLike', 'resolveMaybeAsync'],
  }),
  defineExample({
    id: 'typed-errors',
    pageId: 'example-paging-async',
    anchor: 'typed-errors',
    title: { en: 'Handle typed failures', vi: 'Xử lý lỗi có kiểu' },
    summary: {
      en: 'Narrow every public utility error family and recover from cryptography, secure-random, and paging failures without unsafe fallbacks.',
      vi: 'Thu hẹp mọi nhóm lỗi public của utility và phục hồi từ lỗi mật mã, ngẫu nhiên an toàn và phân trang mà không dùng fallback kém an toàn.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/typed-errors.example.ts?raw')).default,
    relatedSymbols: [
      'SdcoreUtilsErrorOptions',
      'SdcoreUtilsError',
      'SecurityError',
      'ValidationError',
      'SerializationError',
      'UnsafeObjectKeyError',
      'UnsafePropertyPathError',
      'CircularReferenceError',
      'UnsupportedSerializationTypeError',
      'WebCryptoUnavailableError',
      'SecureRandomUnavailableError',
      'EncryptionAuthenticationError',
      'EncryptionFormatError',
      'FilterValidationError',
      'DateParseError',
      'PagingLimitError',
      'PagingResponseError',
      'FilePickerCancelledError',
      'UnsafeUrlProtocolError',
      'EmptySubscribableError',
    ],
  }),
  defineExample({
    id: 'aes-gcm',
    pageId: 'example-security-data',
    anchor: 'aes-gcm',
    title: { en: 'Authenticated AES-GCM', vi: 'AES-GCM có xác thực' },
    summary: {
      en: 'Encrypt JSON-domain data with a fresh IV, a raw AES key, and optional authenticated context.',
      vi: 'Mã hóa dữ liệu miền JSON với IV mới, khóa AES thô và ngữ cảnh xác thực tùy chọn.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/aes-gcm.example.ts?raw')).default,
    relatedSymbols: ['StringUtilities', 'AesGcmEncryptOptions', 'AesGcmDecryptOptions'],
  }),
  defineExample({
    id: 'safe-objects',
    pageId: 'example-security-data',
    anchor: 'safe-objects',
    title: { en: 'Safe object composition and paths', vi: 'Ghép đối tượng và đường dẫn an toàn' },
    summary: {
      en: 'Clone and merge bounded records while rejecting prototype-sensitive property paths.',
      vi: 'Clone và merge record có giới hạn, đồng thời từ chối đường dẫn nhạy cảm với prototype.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/safe-objects.example.ts?raw')).default,
    relatedSymbols: ['ObjectUtilities', 'UnsafePropertyPathError'],
  }),
  defineExample({
    id: 'canonical-hashing',
    pageId: 'example-security-data',
    anchor: 'canonical-hashing',
    title: { en: 'Canonical serialization and hashes', vi: 'Tuần tự hóa chuẩn tắc và hàm băm' },
    summary: {
      en: 'Choose deterministic extended-value serialization, a fast compatibility hash, or cryptographic SHA-256.',
      vi: 'Chọn tuần tự hóa giá trị mở rộng xác định, hash tương thích nhanh hoặc SHA-256 mật mã.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/canonical-hashing.example.ts?raw')).default,
    relatedSymbols: ['canonicalStringify', 'hash32', 'sha256Canonical'],
  }),
  defineExample({
    id: 'dates-dst',
    pageId: 'example-dates-filters',
    anchor: 'dates-dst',
    title: { en: 'Dates and DST-safe differences', vi: 'Ngày và chênh lệch an toàn với DST' },
    summary: {
      en: 'Keep calendar dates, local wall-clock values, and instants separate.',
      vi: 'Tách biệt ngày lịch, thời gian cục bộ và thời điểm tuyệt đối.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/dates-dst.example.ts?raw')).default,
    relatedSymbols: ['DateUtilities', 'AddMonthsOptions'],
  }),
  defineExample({
    id: 'strict-filters',
    pageId: 'example-dates-filters',
    anchor: 'strict-filters',
    title: { en: 'Validate filters before evaluation', vi: 'Xác thực filter trước khi đánh giá' },
    summary: {
      en: 'Validate operands and field hints before deterministic client-side matching.',
      vi: 'Xác thực toán hạng và gợi ý kiểu field trước khi match xác định ở client.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/strict-filters.example.ts?raw')).default,
    relatedSymbols: ['FilterUtilities', 'Filter', 'MatchOptions'],
  }),
  defineExample({
    id: 'numbers-validation',
    pageId: 'example-dates-filters',
    anchor: 'numbers-validation',
    title: { en: 'Explicit number, URL, and UUID validation', vi: 'Xác thực số, URL và UUID tường minh' },
    summary: {
      en: 'Separate parsing from formatting and generic UUID syntax from the v4 contract.',
      vi: 'Tách bước parse khỏi định dạng và UUID generic khỏi contract v4.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/numbers-validation.example.ts?raw')).default,
    relatedSymbols: ['NumberUtilities', 'ValidationUtilities', 'UuidValidationOptions', 'UrlValidationOptions'],
  }),
  defineExample({
    id: 'browser-workflows',
    pageId: 'example-browser-arrays',
    anchor: 'browser-workflows',
    title: { en: 'Browser file and clipboard workflows', vi: 'Luồng file và clipboard trình duyệt' },
    summary: {
      en: 'Use isolated file selection, object-URL cleanup, and Promise-based clipboard failures.',
      vi: 'Dùng chọn file cô lập, dọn object URL và lỗi clipboard dạng Promise.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/browser-workflows.example.ts?raw')).default,
    relatedSymbols: ['BrowserUtilities', 'UploadOptions', 'DownloadOptions'],
  }),
  defineExample({
    id: 'array-operations',
    pageId: 'example-browser-arrays',
    anchor: 'array-operations',
    title: { en: 'Search, union, and page arrays', vi: 'Tìm kiếm, hợp và phân trang mảng' },
    summary: {
      en: 'Use stable first-wins union, bounded tree search, and zero-based slicing.',
      vi: 'Dùng union first-wins ổn định, tìm cây có giới hạn và cắt mảng zero-based.',
    },
    language: 'ts',
    loadSource: async () => (await import('../examples/array-operations.example.ts?raw')).default,
    relatedSymbols: ['ArrayUtilities', 'ArraySearchOptions'],
  }),
] as const;

export const EXAMPLE_PAGES = [
  definePage({
    id: 'example-playgrounds', routeId: 'examples/playgrounds', group: 'examples', order: 0,
    title: { en: 'Interactive playgrounds', vi: 'Playground tương tác' },
    summary: { en: 'Try validation, strict filters, and representative utilities with accessible live results.', vi: 'Thử validation, filter nghiêm ngặt và các tiện ích tiêu biểu với kết quả live dễ tiếp cận.' },
    keywords: { en: ['playground', 'validation', 'filters', 'utilities'], vi: ['playground', 'xác thực', 'filter', 'tiện ích'] },
    anchors: [
      { anchor: 'validation-playground', title: { en: 'Validation playground', vi: 'Playground validation' } },
      { anchor: 'filter-playground', title: { en: 'Filter playground', vi: 'Playground filter' } },
      { anchor: 'utility-playground', title: { en: 'Utility playground', vi: 'Playground tiện ích' } },
    ],
    load: lazyPage(() => import('./examples/playgrounds')),
  }),
  definePage({
    id: 'example-paging-async', routeId: 'examples/paging-async', group: 'examples', order: 1,
    title: { en: 'Paging, async, and errors', vi: 'Phân trang, async và lỗi' },
    summary: { en: 'Production patterns for page-0 APIs, structural async values, and typed failure handling.', vi: 'Mẫu production cho API trang 0, giá trị async dạng cấu trúc và xử lý lỗi có kiểu.' },
    keywords: { en: ['paging', 'async', 'RxJS', 'errors'], vi: ['phân trang', 'async', 'RxJS', 'lỗi'] },
    anchors: [{ anchor: 'example-set', title: { en: 'Runnable examples', vi: 'Ví dụ có thể chạy' } }],
    load: lazyPage(() => import('./examples/paging-async')),
  }),
  definePage({
    id: 'example-security-data', routeId: 'examples/security-data', group: 'examples', order: 2,
    title: { en: 'Security and deterministic data', vi: 'Bảo mật và dữ liệu xác định' },
    summary: { en: 'Authenticated encryption, safe object boundaries, and canonical representations.', vi: 'Mã hóa xác thực, ranh giới đối tượng an toàn và biểu diễn chuẩn tắc.' },
    keywords: { en: ['AES-GCM', 'objects', 'serialization', 'SHA-256'], vi: ['AES-GCM', 'đối tượng', 'tuần tự hóa', 'SHA-256'] },
    anchors: [{ anchor: 'example-set', title: { en: 'Runnable examples', vi: 'Ví dụ có thể chạy' } }],
    load: lazyPage(() => import('./examples/security-data')),
  }),
  definePage({
    id: 'example-dates-filters', routeId: 'examples/dates-filters-validation', group: 'examples', order: 3,
    title: { en: 'Dates, filters, and validation', vi: 'Ngày, filter và xác thực' },
    summary: { en: 'Strict parsing and validation patterns for user-facing applications.', vi: 'Mẫu parse và xác thực nghiêm ngặt cho ứng dụng hướng người dùng.' },
    keywords: { en: ['dates', 'DST', 'filters', 'validation'], vi: ['ngày', 'DST', 'filter', 'xác thực'] },
    anchors: [{ anchor: 'example-set', title: { en: 'Runnable examples', vi: 'Ví dụ có thể chạy' } }],
    load: lazyPage(() => import('./examples/dates-filters-validation')),
  }),
  definePage({
    id: 'example-browser-arrays', routeId: 'examples/browser-arrays', group: 'examples', order: 4,
    title: { en: 'Browser and array workflows', vi: 'Luồng trình duyệt và mảng' },
    summary: { en: 'Practical DOM-bound workflows and predictable collection operations.', vi: 'Luồng phụ thuộc DOM thực tế và thao tác collection có thể dự đoán.' },
    keywords: { en: ['browser', 'files', 'clipboard', 'arrays'], vi: ['trình duyệt', 'file', 'clipboard', 'mảng'] },
    anchors: [{ anchor: 'example-set', title: { en: 'Runnable examples', vi: 'Ví dụ có thể chạy' } }],
    load: lazyPage(() => import('./examples/browser-arrays')),
  }),
] as const;
