import { definePage, lazyPage } from './registry';

export const GUIDE_PAGES = [
  definePage({
    id: 'guide-paging', routeId: 'guides/paging', group: 'guides', order: 0,
    title: { en: 'Zero-based paging', vi: 'Phân trang từ 0' },
    summary: { en: 'Apply the strict page-0 contract and adapt one-based services only at the transport boundary.', vi: 'Áp dụng contract trang 0 nghiêm ngặt và chỉ chuyển đổi dịch vụ one-based tại biên transport.' },
    keywords: { en: ['paging', 'pagination', 'page 0', 'fetchAllByPaging', 'adapter'], vi: ['phân trang', 'trang 0', 'fetchAllByPaging', 'adapter'] },
    anchors: [
      { anchor: 'zero-based-contract', title: { en: 'The zero-based contract', vi: 'Contract zero-based' } },
      { anchor: 'fetch-every-page', title: { en: 'Fetch every page', vi: 'Lấy mọi trang' } },
      { anchor: 'one-based-transport', title: { en: 'Adapt a one-based transport', vi: 'Chuyển đổi transport one-based' } },
      { anchor: 'failure-controls', title: { en: 'Failure controls', vi: 'Cơ chế kiểm soát lỗi' } },
    ],
    load: lazyPage(() => import('./guides/paging')),
  }),
  definePage({
    id: 'guide-encryption', routeId: 'guides/encryption', group: 'guides', order: 1,
    title: { en: 'Encryption and obfuscation', vi: 'Mã hóa và làm rối dữ liệu' },
    summary: { en: 'Choose authenticated AES-GCM for security and keep legacy obfuscation outside trust boundaries.', vi: 'Chọn AES-GCM có xác thực cho bảo mật và giữ cách làm rối cũ ngoài các ranh giới tin cậy.' },
    keywords: { en: ['AES-GCM', 'encryption', 'obfuscation', 'Web Crypto', 'authentication'], vi: ['AES-GCM', 'mã hóa', 'làm rối', 'Web Crypto', 'xác thực'] },
    anchors: [
      { anchor: 'choose-the-right-tool', title: { en: 'Choose the right tool', vi: 'Chọn đúng công cụ' } },
      { anchor: 'authenticated-aes-gcm', title: { en: 'Authenticated AES-GCM', vi: 'AES-GCM có xác thực' } },
      { anchor: 'legacy-obfuscation', title: { en: 'Legacy obfuscation', vi: 'Cơ chế làm rối cũ' } },
      { anchor: 'handle-crypto-errors', title: { en: 'Handle cryptographic errors', vi: 'Xử lý lỗi mật mã' } },
    ],
    load: lazyPage(() => import('./guides/encryption')),
  }),
  definePage({
    id: 'guide-safe-objects', routeId: 'guides/safe-objects', group: 'guides', order: 2,
    title: { en: 'Safe objects and paths', vi: 'Đối tượng và đường dẫn an toàn' },
    summary: { en: 'Reject prototype-sensitive keys and traverse only bounded, own data properties.', vi: 'Từ chối khóa nhạy cảm với prototype và chỉ duyệt các data property own có giới hạn.' },
    keywords: { en: ['prototype pollution', 'property path', 'clone', 'merge', 'safe object'], vi: ['prototype pollution', 'đường dẫn thuộc tính', 'clone', 'merge', 'đối tượng an toàn'] },
    anchors: [
      { anchor: 'unsafe-keys', title: { en: 'Unsafe keys', vi: 'Khóa không an toàn' } },
      { anchor: 'safe-property-paths', title: { en: 'Safe property paths', vi: 'Đường dẫn thuộc tính an toàn' } },
      { anchor: 'clone-and-merge', title: { en: 'Clone and merge', vi: 'Clone và merge' } },
      { anchor: 'boundary-limit', title: { en: 'What this boundary does not do', vi: 'Ranh giới này không làm gì' } },
    ],
    load: lazyPage(() => import('./guides/safe-objects')),
  }),
  definePage({
    id: 'guide-serialization', routeId: 'guides/serialization-hashing', group: 'guides', order: 3,
    title: { en: 'Serialization and hashing', vi: 'Tuần tự hóa và băm' },
    summary: { en: 'Select a deterministic representation and the correct hash for compatibility or security.', vi: 'Chọn biểu diễn xác định và hàm băm phù hợp cho tương thích hoặc bảo mật.' },
    keywords: { en: ['stableStringify', 'canonicalStringify', 'hash32', 'SHA-256', 'serialization'], vi: ['stableStringify', 'canonicalStringify', 'hash32', 'SHA-256', 'tuần tự hóa'] },
    anchors: [
      { anchor: 'choose-a-serializer', title: { en: 'Choose a serializer', vi: 'Chọn bộ tuần tự hóa' } },
      { anchor: 'canonical-values', title: { en: 'Canonical extended values', vi: 'Giá trị mở rộng chuẩn tắc' } },
      { anchor: 'choose-a-hash', title: { en: 'Choose a hash', vi: 'Chọn hàm băm' } },
      { anchor: 'unsupported-values', title: { en: 'Unsupported values', vi: 'Giá trị không được hỗ trợ' } },
    ],
    load: lazyPage(() => import('./guides/serialization-hashing')),
  }),
  definePage({
    id: 'guide-dates', routeId: 'guides/dates-time-zones', group: 'guides', order: 4,
    title: { en: 'Dates, time zones, and DST', vi: 'Ngày, múi giờ và DST' },
    summary: { en: 'Keep calendar dates, local wall-clock values, and instants distinct.', vi: 'Phân biệt ngày lịch, thời gian cục bộ và thời điểm tuyệt đối.' },
    keywords: { en: ['date', 'timezone', 'DST', 'instant', 'calendar'], vi: ['ngày', 'múi giờ', 'DST', 'thời điểm', 'lịch'] },
    anchors: [
      { anchor: 'three-time-concepts', title: { en: 'Three time concepts', vi: 'Ba khái niệm thời gian' } },
      { anchor: 'strict-parsing', title: { en: 'Strict parsing', vi: 'Phân tích nghiêm ngặt' } },
      { anchor: 'dst-differences', title: { en: 'DST-safe differences', vi: 'Tính chênh lệch an toàn với DST' } },
      { anchor: 'calendar-arithmetic', title: { en: 'Calendar arithmetic', vi: 'Phép toán lịch' } },
    ],
    load: lazyPage(() => import('./guides/dates-time-zones')),
  }),
  definePage({
    id: 'guide-filters', routeId: 'guides/filters', group: 'guides', order: 5,
    title: { en: 'Strict filters', vi: 'Filter nghiêm ngặt' },
    summary: { en: 'Validate complete filter trees before deterministic client-side evaluation.', vi: 'Xác thực toàn bộ cây filter trước khi đánh giá xác định ở client.' },
    keywords: { en: ['filter', 'validateFilter', 'evaluateFilter', 'timestamp', 'strict'], vi: ['filter', 'validateFilter', 'evaluateFilter', 'timestamp', 'nghiêm ngặt'] },
    anchors: [
      { anchor: 'validate-first', title: { en: 'Validate first', vi: 'Xác thực trước' } },
      { anchor: 'typed-comparison', title: { en: 'Typed comparison', vi: 'So sánh có kiểu' } },
      { anchor: 'timestamp-units', title: { en: 'Timestamp units', vi: 'Đơn vị timestamp' } },
      { anchor: 'missing-values', title: { en: 'Missing values', vi: 'Giá trị bị thiếu' } },
    ],
    load: lazyPage(() => import('./guides/filters')),
  }),
  definePage({
    id: 'guide-browser', routeId: 'guides/browser-workflows', group: 'guides', order: 6,
    title: { en: 'Browser workflows', vi: 'Luồng xử lý trình duyệt' },
    summary: { en: 'Use file, download, clipboard, and capability APIs with explicit browser boundaries.', vi: 'Dùng API file, tải xuống, clipboard và capability với ranh giới trình duyệt tường minh.' },
    keywords: { en: ['browser', 'upload', 'download', 'clipboard', 'incognito'], vi: ['trình duyệt', 'tải lên', 'tải xuống', 'clipboard', 'ẩn danh'] },
    anchors: [
      { anchor: 'file-picker', title: { en: 'File picker', vi: 'Trình chọn file' } },
      { anchor: 'safe-downloads', title: { en: 'Safe downloads', vi: 'Tải xuống an toàn' } },
      { anchor: 'clipboard', title: { en: 'Clipboard', vi: 'Clipboard' } },
      { anchor: 'private-mode', title: { en: 'Private-mode detection', vi: 'Phát hiện chế độ riêng tư' } },
    ],
    load: lazyPage(() => import('./guides/browser-workflows')),
  }),
  definePage({
    id: 'guide-validation', routeId: 'guides/validation-numbers', group: 'guides', order: 7,
    title: { en: 'Validation and numbers', vi: 'Xác thực và số' },
    summary: { en: 'Use explicit validators and locale-aware formatting without turning presentation into parsing.', vi: 'Dùng validator tường minh và định dạng theo locale mà không biến phần hiển thị thành bước phân tích dữ liệu.' },
    keywords: { en: ['validation', 'URL', 'UUID', 'numbers', 'formatting'], vi: ['xác thực', 'URL', 'UUID', 'số', 'định dạng'] },
    anchors: [
      { anchor: 'strict-validation', title: { en: 'Strict validation', vi: 'Xác thực nghiêm ngặt' } },
      { anchor: 'url-and-uuid', title: { en: 'URLs and UUIDs', vi: 'URL và UUID' } },
      { anchor: 'number-formatting', title: { en: 'Number formatting', vi: 'Định dạng số' } },
      { anchor: 'handle-validation-errors', title: { en: 'Handle validation errors', vi: 'Xử lý lỗi xác thực' } },
    ],
    load: lazyPage(() => import('./guides/validation-numbers')),
  }),
  definePage({
    id: 'guide-async', routeId: 'guides/async-rxjs', group: 'guides', order: 8,
    title: { en: 'MaybeAsync and RxJS', vi: 'MaybeAsync và RxJS' },
    summary: { en: 'Bridge values, promises, and structural subscribables without a runtime RxJS dependency.', vi: 'Kết nối giá trị, promise và subscribable dạng cấu trúc mà không phụ thuộc RxJS lúc runtime.' },
    keywords: { en: ['MaybeAsync', 'Promise', 'SubscribableLike', 'RxJS', 'Observable'], vi: ['MaybeAsync', 'Promise', 'SubscribableLike', 'RxJS', 'Observable'] },
    anchors: [
      { anchor: 'structural-contract', title: { en: 'The structural contract', vi: 'Contract dạng cấu trúc' } },
      { anchor: 'resolve-first-value', title: { en: 'Resolve the first value', vi: 'Nhận giá trị đầu tiên' } },
      { anchor: 'normalize-subscription', title: { en: 'Normalize subscription', vi: 'Chuẩn hóa subscription' } },
      { anchor: 'rxjs-boundary', title: { en: 'The RxJS boundary', vi: 'Ranh giới RxJS' } },
    ],
    load: lazyPage(() => import('./guides/async-rxjs')),
  }),
] as const;
