import type { ApiEntry, ApiMember } from '../types';
import {
  commonErrors,
  createEntry,
  createMember,
  deprecated,
  type MemberSpec,
  type ParameterSpec,
  type PageId,
} from './shared';

const FNS_IMPORT = '@sdcorejs/utils/fns' as const;

const parameter = (
  name: string,
  type: string,
  en: string,
  vi: string,
  options: { readonly optional?: boolean; readonly defaultValue?: string } = {},
): ParameterSpec => ({ name, type, en, vi, ...options });

const valueParameter = parameter(
  'value',
  'unknown',
  'Value to inspect, convert, serialize, or validate.',
  'Giá trị cần kiểm tra, chuyển đổi, tuần tự hóa hoặc xác thực.',
);

const filterOptionsParameter = parameter(
  'options',
  'MatchOptions<T>',
  'Optional strict type, timestamp, depth, path, missing-value, and reference-time policies.',
  'Chính sách tùy chọn về kiểu nghiêm ngặt, timestamp, độ sâu, đường dẫn, giá trị thiếu và thời gian tham chiếu.',
  { optional: true, defaultValue: 'undefined' },
);

const strictFilterRuntimeEn = [
  'Filter graphs are validated before evaluation; malformed definitions throw instead of becoming false matches.',
  'Date-like numeric values require an explicit seconds or milliseconds unit unless deprecated legacy inference is enabled.',
] as const;

const strictFilterRuntimeVi = [
  'Đồ thị bộ lọc được xác thực trước khi đánh giá; định nghĩa sai sẽ ném lỗi thay vì biến thành kết quả không khớp.',
  'Giá trị ngày dạng số cần chỉ rõ đơn vị giây hoặc mili giây, trừ khi bật cơ chế suy đoán cũ đã deprecated.',
] as const;

const filterSecurityEn = [
  'Field paths traverse own data properties only, reject prototype-sensitive segments, and do not invoke getters by default.',
  'Client-side filtering selects data only; it is never an authentication or authorization boundary.',
] as const;

const filterSecurityVi = [
  'Đường dẫn field chỉ duyệt data property sở hữu, từ chối segment nhạy cảm với prototype và mặc định không gọi getter.',
  'Lọc phía client chỉ chọn dữ liệu; tuyệt đối không phải ranh giới xác thực hoặc phân quyền.',
] as const;

const filterMemberSpecs = [
  {
    name: 'match',
    signature: '<T = unknown>(filters: Filter<T>[], item: T, options?: MatchOptions<T>) => boolean',
    en: 'Evaluates an implicit-AND list of filters against one item; an empty or missing list matches.',
    vi: 'Đánh giá danh sách bộ lọc AND ngầm định trên một phần tử; danh sách rỗng hoặc thiếu được xem là khớp.',
    parameters: [
      parameter('filters', 'Filter<T>[]', 'Top-level filters combined with AND.', 'Các bộ lọc cấp cao nhất được kết hợp bằng AND.'),
      parameter('item', 'T', 'Item being selected.', 'Phần tử được chọn lọc.'),
      filterOptionsParameter,
    ],
    returnsEn: '`true` when every supplied filter matches; `true` for an empty, `null`, or `undefined` runtime list.',
    returnsVi: '`true` khi mọi bộ lọc đều khớp; cũng là `true` với danh sách runtime rỗng, `null` hoặc `undefined`.',
    throws: [commonErrors.filter, commonErrors.unsafePath],
    runtimeEn: strictFilterRuntimeEn,
    runtimeVi: strictFilterRuntimeVi,
    securityEn: filterSecurityEn,
    securityVi: filterSecurityVi,
    exampleIds: ['strict-filters'],
  },
  {
    name: 'evaluate',
    signature: '<T = unknown>(filter: Filter<T>, item: T, options?: MatchOptions<T>) => boolean',
    en: 'Compatibility form that evaluates one filter using the historical `(filter, item)` argument order.',
    vi: 'Dạng tương thích đánh giá một bộ lọc theo thứ tự đối số lịch sử `(filter, item)`.',
    parameters: [
      parameter('filter', 'Filter<T>', 'Filter definition to validate and evaluate.', 'Định nghĩa bộ lọc cần xác thực và đánh giá.'),
      parameter('item', 'T', 'Item being selected.', 'Phần tử được chọn lọc.'),
      filterOptionsParameter,
    ],
    returnsEn: '`true` when the validated filter matches the item.',
    returnsVi: '`true` khi bộ lọc đã xác thực khớp phần tử.',
    throws: [commonErrors.filter, commonErrors.unsafePath],
    runtimeEn: strictFilterRuntimeEn,
    runtimeVi: strictFilterRuntimeVi,
    securityEn: filterSecurityEn,
    securityVi: filterSecurityVi,
    exampleIds: ['strict-filters'],
  },
  {
    name: 'evaluateFilter',
    signature: '<T = unknown>(item: T, filter: unknown, options?: MatchOptions<T>) => boolean',
    en: 'Validates an unknown filter and evaluates it against one item using item-first argument order.',
    vi: 'Xác thực bộ lọc chưa biết và đánh giá trên một phần tử theo thứ tự đối số item trước.',
    parameters: [
      parameter('item', 'T', 'Item being selected.', 'Phần tử được chọn lọc.'),
      parameter('filter', 'unknown', 'Untrusted filter definition to validate before evaluation.', 'Định nghĩa bộ lọc không tin cậy cần xác thực trước khi đánh giá.'),
      filterOptionsParameter,
    ],
    returnsEn: '`true` when the validated filter matches; invalid entity values deterministically do not match.',
    returnsVi: '`true` khi bộ lọc đã xác thực khớp; giá trị entity không hợp lệ luôn được xem là không khớp.',
    throws: [commonErrors.filter, commonErrors.unsafePath],
    runtimeEn: strictFilterRuntimeEn,
    runtimeVi: strictFilterRuntimeVi,
    securityEn: filterSecurityEn,
    securityVi: filterSecurityVi,
    exampleIds: ['strict-filters'],
  },
  {
    name: 'validateFilter',
    signature: '<T = unknown>(filter: unknown, options?: MatchOptions<T>) => ValidatedFilter<T>',
    en: 'Strictly validates and safely clones an unknown filter graph.',
    vi: 'Xác thực nghiêm ngặt và sao chép an toàn một đồ thị bộ lọc chưa biết.',
    parameters: [
      parameter('filter', 'unknown', 'Potentially untrusted filter definition.', 'Định nghĩa bộ lọc có thể không tin cậy.'),
      filterOptionsParameter,
    ],
    returnsEn: 'A branded `ValidatedFilter<T>` clone containing supported data properties only.',
    returnsVi: 'Bản sao `ValidatedFilter<T>` có brand, chỉ chứa các data property được hỗ trợ.',
    throws: [commonErrors.filter, commonErrors.unsafePath],
    runtimeEn: [
      'The default logical-filter depth is 32; cycles, accessors, invalid operands, unsupported operators, and invalid option values are rejected.',
      ...strictFilterRuntimeEn,
    ],
    runtimeVi: [
      'Độ sâu bộ lọc logic mặc định là 32; chu trình, accessor, toán hạng sai, operator không hỗ trợ và option sai đều bị từ chối.',
      ...strictFilterRuntimeVi,
    ],
    securityEn: filterSecurityEn,
    securityVi: filterSecurityVi,
    exampleIds: ['strict-filters', 'typed-errors'],
  },
  {
    name: 'resolveData',
    signature: '(filter: FilterHasData, entity: unknown, options?: MatchOptions) => unknown',
    en: 'Resolves a literal, field reference, today sentinel, or relative-date filter operand.',
    vi: 'Phân giải toán hạng bộ lọc dạng literal, tham chiếu field, mốc hôm nay hoặc ngày tương đối.',
    parameters: [
      parameter('filter', 'FilterHasData', 'Single-value filter whose operand is resolved.', 'Bộ lọc đơn trị có toán hạng cần phân giải.'),
      parameter('entity', 'unknown', 'Entity used for a `dataType: "field"` reference.', 'Entity dùng cho tham chiếu `dataType: "field"`.'),
      parameter('options', 'MatchOptions', 'Optional path and deterministic reference-time policies.', 'Chính sách tùy chọn về đường dẫn và thời gian tham chiếu xác định.', { optional: true, defaultValue: 'undefined' }),
    ],
    returnsEn: 'The resolved operand, or `undefined` when a referenced own property is absent or inaccessible.',
    returnsVi: 'Toán hạng đã phân giải, hoặc `undefined` khi own property được tham chiếu bị thiếu hay không thể truy cập.',
    throws: [commonErrors.filter, commonErrors.unsafePath],
    runtimeEn: ['Relative day/week/month operands anchor at the start of the reference day; hours anchor at the exact reference time.'],
    runtimeVi: ['Toán hạng ngày/tuần/tháng tương đối neo tại đầu ngày tham chiếu; giờ neo tại đúng thời điểm tham chiếu.'],
    securityEn: filterSecurityEn,
    securityVi: filterSecurityVi,
    exampleIds: ['strict-filters'],
  },
  {
    name: 'resolveRelativeDate',
    signature: '(relative: DateRelative, now?: Date) => Date',
    en: 'Resolves a validated relative hour, day, week, or month specification to a Date.',
    vi: 'Phân giải đặc tả giờ, ngày, tuần hoặc tháng tương đối hợp lệ thành Date.',
    parameters: [
      parameter('relative', 'DateRelative', 'Positive safe-integer relative offset specification.', 'Đặc tả độ lệch tương đối bằng số nguyên an toàn dương.'),
      parameter('now', 'Date', 'Reference time.', 'Thời gian tham chiếu.', { optional: true, defaultValue: 'new Date()' }),
    ],
    returnsEn: 'A new resolved `Date`; calendar units use local calendar arithmetic.',
    returnsVi: 'Một `Date` mới đã phân giải; các đơn vị lịch dùng phép tính lịch địa phương.',
    throws: [commonErrors.filter],
    runtimeEn: ['Hour offsets retain the reference time-of-day; day, week, and month offsets begin at local midnight.'],
    runtimeVi: ['Độ lệch giờ giữ nguyên giờ trong ngày; độ lệch ngày, tuần và tháng bắt đầu tại nửa đêm địa phương.'],
    securityEn: ['Pass a fixed `now` for deterministic evaluation; do not use relative client time for authorization.'],
    securityVi: ['Truyền `now` cố định để đánh giá xác định; không dùng thời gian tương đối phía client cho phân quyền.'],
    exampleIds: ['strict-filters'],
  },
  {
    name: 'toEpoch',
    signature: '(value: unknown, options?: ToEpochOptions) => number | null',
    en: 'Converts a strict supported date representation to epoch milliseconds.',
    vi: 'Chuyển biểu diễn ngày được hỗ trợ theo quy tắc nghiêm ngặt sang epoch mili giây.',
    parameters: [
      valueParameter,
      parameter('options', 'ToEpochOptions', 'Explicit timestamp-unit policy.', 'Chính sách đơn vị timestamp tường minh.', { optional: true, defaultValue: '{}' }),
    ],
    returnsEn: 'Finite epoch milliseconds, or `null` when the representation cannot be resolved.',
    returnsVi: 'Epoch mili giây hữu hạn, hoặc `null` khi không thể phân giải biểu diễn.',
    runtimeEn: ['Numeric values and numeric strings require `timestampUnit`; strict local dates, local date-times, and explicit instants are supported.'],
    runtimeVi: ['Số và chuỗi số cần `timestampUnit`; hỗ trợ ngày địa phương, ngày-giờ địa phương nghiêm ngặt và instant tường minh.'],
    securityEn: ['Prefer explicit units. Magnitude-based legacy inference can reinterpret valid pre-2001 millisecond timestamps.'],
    securityVi: ['Ưu tiên đơn vị tường minh. Suy đoán cũ theo độ lớn có thể diễn giải sai timestamp mili giây hợp lệ trước năm 2001.'],
    exampleIds: ['strict-filters'],
  },
  {
    name: 'relativeDate',
    signature: '(amount: number, direction: DateRelative["direction"], unit: DateRelative["unit"]) => DateRelative',
    en: 'Builds and validates a relative-date specification.',
    vi: 'Tạo và xác thực một đặc tả ngày tương đối.',
    parameters: [
      parameter('amount', 'number', 'Positive safe-integer offset magnitude.', 'Độ lớn offset là số nguyên an toàn dương.'),
      parameter('direction', 'DateRelative["direction"]', 'Either `previous` or `next`.', 'Một trong `previous` hoặc `next`.'),
      parameter('unit', 'DateRelative["unit"]', 'One of `hour`, `day`, `week`, or `month`.', 'Một trong `hour`, `day`, `week` hoặc `month`.'),
    ],
    returnsEn: 'A validated `DateRelative` object.',
    returnsVi: 'Một object `DateRelative` đã xác thực.',
    throws: [commonErrors.filter],
    runtimeEn: ['The amount must be greater than zero and within the safe-integer range.'],
    runtimeVi: ['Amount phải lớn hơn 0 và nằm trong miền số nguyên an toàn.'],
    securityEn: ['This describes data selection only and must not determine access rights.'],
    securityVi: ['Đặc tả này chỉ mô tả chọn dữ liệu và không được quyết định quyền truy cập.'],
    exampleIds: ['strict-filters'],
  },
  {
    name: 'isDateRelative',
    signature: '(value: unknown) => value is DateRelative',
    en: 'Checks the exact runtime shape of a relative-date specification.',
    vi: 'Kiểm tra chính xác cấu trúc runtime của một đặc tả ngày tương đối.',
    parameters: [valueParameter],
    returnsEn: '`true` only for a positive safe-integer amount, supported direction, and supported unit.',
    returnsVi: '`true` chỉ khi amount là số nguyên an toàn dương, direction và unit đều được hỗ trợ.',
    runtimeEn: ['Own data properties are inspected without invoking accessors.'],
    runtimeVi: ['Chỉ kiểm tra own data property mà không gọi accessor.'],
    securityEn: ['Use `validateFilter` for complete filter-graph validation.'],
    securityVi: ['Dùng `validateFilter` để xác thực toàn bộ đồ thị bộ lọc.'],
    exampleIds: ['strict-filters'],
  },
] as const satisfies readonly MemberSpec[];

const serializationErrors = [commonErrors.unsupported, commonErrors.circular, commonErrors.unsafeKey] as const;

const serializationOptionsParameter = parameter(
  'options',
  'CanonicalStringifyOptions',
  'Canonical traversal options.',
  'Tùy chọn duyệt canonical.',
  { optional: true, defaultValue: '{}' },
);

const stableStringifySpec = {
  name: 'stableStringify',
  signature: '(value: unknown, options?: StableStringifyOptions) => string',
  en: 'Deterministically serializes the strict JSON-compatible domain with sorted object keys.',
  vi: 'Tuần tự hóa xác định miền tương thích JSON nghiêm ngặt với khóa object được sắp xếp.',
  parameters: [
    valueParameter,
    parameter('options', 'StableStringifyOptions', 'Bounded traversal options.', 'Tùy chọn giới hạn duyệt.', { optional: true, defaultValue: '{}' }),
  ],
  returnsEn: 'A deterministic JSON string; `Date` values encode as ISO strings for compatibility.',
  returnsVi: 'Chuỗi JSON xác định; giá trị `Date` được mã hóa thành chuỗi ISO để tương thích.',
  throws: serializationErrors,
  runtimeEn: ['Rejects unsupported primitives, non-finite numbers, sparse arrays, accessors, class instances, collections, binary values, and cycles.'],
  runtimeVi: ['Từ chối primitive không hỗ trợ, số không hữu hạn, array thưa, accessor, class instance, collection, binary và chu trình.'],
  securityEn: ['Data properties are read without invoking getters; prototype-sensitive keys are rejected.'],
  securityVi: ['Đọc data property mà không gọi getter; khóa nhạy cảm với prototype bị từ chối.'],
  exampleIds: ['canonical-hashing', 'typed-errors'],
} as const satisfies MemberSpec;

const canonicalStringifySpec = {
  name: 'canonicalStringify',
  signature: '(value: unknown, options?: CanonicalStringifyOptions) => string',
  en: 'Canonically encodes supported extended JavaScript values with collision-safe type tags.',
  vi: 'Mã hóa canonical các giá trị JavaScript mở rộng được hỗ trợ bằng type tag chống va chạm.',
  parameters: [valueParameter, serializationOptionsParameter],
  returnsEn: 'A deterministic tagged JSON string independent of object, Map, and Set insertion order.',
  returnsVi: 'Chuỗi JSON có tag xác định, độc lập với thứ tự chèn của object, Map và Set.',
  throws: serializationErrors,
  runtimeEn: ['Supports primitive edge cases, BigInt, Date, RegExp, Map, Set, ArrayBuffer, typed arrays, and sparse-array holes; rejects Blob/File, class instances, accessors, functions, symbols, and cycles.'],
  runtimeVi: ['Hỗ trợ trường hợp primitive đặc biệt, BigInt, Date, RegExp, Map, Set, ArrayBuffer, typed array và lỗ array; từ chối Blob/File, class instance, accessor, function, symbol và chu trình.'],
  securityEn: ['Canonical encoding prevents type-tag ambiguity but does not itself authenticate data.'],
  securityVi: ['Mã hóa canonical ngăn mơ hồ type tag nhưng tự nó không xác thực dữ liệu.'],
  exampleIds: ['canonical-hashing', 'typed-errors'],
} as const satisfies MemberSpec;

const hash32Spec = {
  name: 'hash32',
  signature: '(value: unknown) => string',
  en: 'Computes the legacy fast 32-bit hash over stable serialization.',
  vi: 'Tính hash 32-bit nhanh kiểu cũ trên kết quả tuần tự hóa ổn định.',
  parameters: [valueParameter],
  returnsEn: 'A deterministic string prefixed with `h`.',
  returnsVi: 'Chuỗi xác định có tiền tố `h`.',
  throws: serializationErrors,
  runtimeEn: ['Uses `stableStringify`, so only its documented strict domain is accepted.'],
  runtimeVi: ['Dùng `stableStringify`, nên chỉ chấp nhận miền nghiêm ngặt đã được tài liệu hóa của hàm đó.'],
  securityEn: ['Non-cryptographic and collision-prone: never use for signatures, authentication, authorization, or untrusted persistent identities.'],
  securityVi: ['Không phải mật mã và có thể va chạm: không dùng cho chữ ký, xác thực, phân quyền hoặc định danh lưu trữ từ dữ liệu không tin cậy.'],
  exampleIds: ['canonical-hashing'],
} as const satisfies MemberSpec;

const hashSpec = {
  ...hash32Spec,
  name: 'hash',
  signature: '(value: unknown) => string',
  en: 'Compatibility alias for the legacy 32-bit `hash32` algorithm.',
  vi: 'Alias tương thích của thuật toán 32-bit cũ `hash32`.',
  deprecation: deprecated(
    'hash32',
    'Prefer `hash32` for explicit non-cryptographic intent or `sha256Canonical` when collision resistance is required.',
    'Ưu tiên `hash32` để thể hiện rõ mục đích phi mật mã hoặc `sha256Canonical` khi cần chống va chạm.',
  ),
} as const satisfies MemberSpec;

const sha256CanonicalSpec = {
  name: 'sha256Canonical',
  signature: '(value: unknown, options?: CanonicalStringifyOptions) => Promise<string>',
  en: 'Returns the SHA-256 digest of the canonical value encoding.',
  vi: 'Trả về digest SHA-256 của biểu diễn canonical của giá trị.',
  parameters: [valueParameter, serializationOptionsParameter],
  returnsEn: 'A promise for a lowercase 64-character hexadecimal SHA-256 digest.',
  returnsVi: 'Promise trả về digest SHA-256 hex chữ thường dài 64 ký tự.',
  throws: [...serializationErrors, commonErrors.webCrypto],
  runtimeEn: ['Requires `globalThis.crypto.subtle`; there is no weak hashing fallback.'],
  runtimeVi: ['Cần `globalThis.crypto.subtle`; không có fallback hash yếu.'],
  securityEn: ['SHA-256 is collision-resistant, but callers must still define trusted canonical inputs and an authentication protocol when needed.'],
  securityVi: ['SHA-256 chống va chạm, nhưng bên gọi vẫn phải xác định input canonical đáng tin và giao thức xác thực khi cần.'],
  exampleIds: ['canonical-hashing', 'typed-errors'],
} as const satisfies MemberSpec;

const sha256BlobSpec = {
  name: 'sha256Blob',
  signature: '(blob: Blob) => Promise<string>',
  en: 'Hashes the actual bytes of a Blob or File with SHA-256.',
  vi: 'Hash các byte thực của Blob hoặc File bằng SHA-256.',
  parameters: [parameter('blob', 'Blob', 'Blob or File whose complete byte content is hashed.', 'Blob hoặc File có toàn bộ nội dung byte cần hash.')],
  returnsEn: 'A promise for a lowercase 64-character hexadecimal SHA-256 digest.',
  returnsVi: 'Promise trả về digest SHA-256 hex chữ thường dài 64 ký tự.',
  throws: [commonErrors.unsupported, commonErrors.webCrypto],
  runtimeEn: ['Reads `blob.arrayBuffer()` and requires `globalThis.crypto.subtle`; there is no weak fallback.'],
  runtimeVi: ['Đọc `blob.arrayBuffer()` và cần `globalThis.crypto.subtle`; không có fallback yếu.'],
  securityEn: ['Hash bytes, not filename or MIME metadata, when checking file identity; a hash does not prove content safety.'],
  securityVi: ['Hash byte thay vì tên file hay MIME metadata khi kiểm tra định danh file; hash không chứng minh nội dung an toàn.'],
  exampleIds: ['canonical-hashing', 'typed-errors'],
} as const satisfies MemberSpec;

const parseQueryParamsSpec = {
  name: 'parseQueryParams',
  signature: '(queryString?: string) => Record<string, string>',
  en: 'Parses URL query parameters into a safe own-property record.',
  vi: 'Phân tích query parameter URL thành record own-property an toàn.',
  parameters: [parameter('queryString', 'string', 'Query string, with or without a leading `?`.', 'Chuỗi query, có thể có hoặc không có `?` đầu.', { optional: true, defaultValue: 'undefined' })],
  returnsEn: 'A decoded record; repeated keys keep the last value according to `URLSearchParams.forEach` assignment.',
  returnsVi: 'Record đã decode; khóa lặp giữ giá trị cuối theo phép gán của `URLSearchParams.forEach`.',
  throws: [commonErrors.unsafeKey],
  runtimeEn: ['Missing or empty input returns an empty ordinary object.'],
  runtimeVi: ['Input thiếu hoặc rỗng trả về object thường rỗng.'],
  securityEn: ['Prototype-sensitive parameter names are rejected rather than assigned. Query values remain untrusted input.'],
  securityVi: ['Tên parameter nhạy cảm với prototype bị từ chối thay vì gán. Giá trị query vẫn là input không tin cậy.'],
  exampleIds: ['safe-objects', 'typed-errors'],
} as const satisfies MemberSpec;

const getNestedValueSpec = {
  name: 'getNestedValue',
  signature: '<T = unknown>(obj: unknown, path: string, options?: PropertyPathOptions) => T | undefined',
  en: 'Safely resolves dot or numeric/quoted-bracket paths through own properties.',
  vi: 'Phân giải an toàn đường dẫn dấu chấm hoặc bracket số/có quote qua own property.',
  parameters: [
    parameter('obj', 'unknown', 'Object graph to traverse.', 'Đồ thị object cần duyệt.'),
    parameter('path', 'string', 'Strict property path such as `user.name` or `items[0].name`.', 'Đường dẫn property nghiêm ngặt như `user.name` hoặc `items[0].name`.'),
    parameter('options', 'PropertyPathOptions', 'Depth and accessor policy.', 'Chính sách độ sâu và accessor.', { optional: true, defaultValue: '{}' }),
  ],
  returnsEn: 'The own-property value, or `undefined` when a segment is absent or an accessor is disallowed.',
  returnsVi: 'Giá trị own-property, hoặc `undefined` khi thiếu segment hay accessor không được phép.',
  throws: [commonErrors.unsafePath],
  runtimeEn: ['The default maximum path depth is 32; getters are not invoked unless `allowAccessors` is explicitly true.'],
  runtimeVi: ['Độ sâu đường dẫn tối đa mặc định là 32; getter không được gọi trừ khi đặt rõ `allowAccessors: true`.'],
  securityEn: ['Inherited properties, prototype objects, malformed paths, and `__proto__`/`prototype`/`constructor` segments are rejected or inaccessible.'],
  securityVi: ['Inherited property, prototype object, đường dẫn sai và segment `__proto__`/`prototype`/`constructor` bị từ chối hoặc không thể truy cập.'],
  exampleIds: ['safe-objects', 'typed-errors'],
} as const satisfies MemberSpec;

const isPlainObjectSpec = {
  name: 'isPlainObject',
  signature: '(value: unknown) => value is PlainRecord',
  en: 'Checks for an object literal or null-prototype record.',
  vi: 'Kiểm tra object literal hoặc record có prototype null.',
  parameters: [valueParameter],
  returnsEn: '`true` only when the prototype is `Object.prototype` or `null`.',
  returnsVi: '`true` chỉ khi prototype là `Object.prototype` hoặc `null`.',
  runtimeEn: ['Arrays, functions, class instances, and built-in objects return `false`.'],
  runtimeVi: ['Array, function, class instance và object built-in trả về `false`.'],
  securityEn: ['This is a shape guard, not a trust or authorization decision.'],
  securityVi: ['Đây là guard cấu trúc, không phải quyết định tin cậy hay phân quyền.'],
  exampleIds: ['safe-objects'],
} as const satisfies MemberSpec;

const cloneSpec = {
  name: 'clone',
  signature: '<T>(value: T, options?: ObjectTraversalOptions) => T',
  en: 'Deeply clones arrays and record-like objects with bounded, cycle-aware traversal.',
  vi: 'Sao chép sâu array và object dạng record bằng phép duyệt có giới hạn và nhận biết chu trình.',
  parameters: [
    parameter('value', 'T', 'Value graph to clone.', 'Đồ thị giá trị cần sao chép.'),
    parameter('options', 'ObjectTraversalOptions', 'Traversal depth limit.', 'Giới hạn độ sâu duyệt.', { optional: true, defaultValue: '{}' }),
  ],
  returnsEn: 'A cloned graph; supported cycles and sparse-array holes are preserved, while non-plain leaves retain their reference.',
  returnsVi: 'Đồ thị đã sao chép; chu trình được hỗ trợ và lỗ array được giữ, còn leaf không phải plain object giữ nguyên tham chiếu.',
  throws: [commonErrors.validation, commonErrors.unsafeKey],
  runtimeEn: ['The default maximum depth is 1,000. Custom-prototype record-like objects are sanitized to safe records; genuine class instances remain leaves.'],
  runtimeVi: ['Độ sâu tối đa mặc định là 1.000. Object dạng record có custom prototype được làm sạch thành record an toàn; class instance thực vẫn là leaf.'],
  securityEn: ['Inherited properties and accessors are not copied; prototype-sensitive enumerable keys are rejected.'],
  securityVi: ['Không sao chép inherited property hay accessor; khóa enumerable nhạy cảm với prototype bị từ chối.'],
  exampleIds: ['safe-objects', 'typed-errors'],
} as const satisfies MemberSpec;

const mergeSpec = {
  name: 'merge',
  signature: '<T>(defaultValue: T, overrideValue: T | undefined, options?: ObjectTraversalOptions) => T',
  en: 'Deeply merges plain records while cloning selected record and array data.',
  vi: 'Merge sâu plain record đồng thời sao chép dữ liệu record và array được chọn.',
  parameters: [
    parameter('defaultValue', 'T', 'Fallback value graph.', 'Đồ thị giá trị mặc định.'),
    parameter('overrideValue', 'T | undefined', 'Override graph; `undefined` inherits the default and `null` overrides it.', 'Đồ thị ghi đè; `undefined` kế thừa mặc định còn `null` ghi đè.'),
    parameter('options', 'ObjectTraversalOptions', 'Traversal depth limit.', 'Giới hạn độ sâu duyệt.', { optional: true, defaultValue: '{}' }),
  ],
  returnsEn: 'A merged graph; arrays replace rather than merge by index and cyclic plain graphs are preserved.',
  returnsVi: 'Đồ thị đã merge; array thay thế thay vì merge theo index và chu trình plain object được giữ.',
  throws: [commonErrors.validation, commonErrors.unsafeKey],
  runtimeEn: ['Date, Map, Set, class instances, and other non-plain leaves retain the selected reference.'],
  runtimeVi: ['Date, Map, Set, class instance và leaf không phải plain object khác giữ tham chiếu được chọn.'],
  securityEn: ['Only own data properties participate; prototype-sensitive keys and accessors are rejected.'],
  securityVi: ['Chỉ own data property tham gia; khóa nhạy cảm với prototype và accessor bị từ chối.'],
  exampleIds: ['safe-objects', 'typed-errors'],
} as const satisfies MemberSpec;

const deepMergeSpec = {
  name: 'deepMerge',
  signature: '<T>(...sources: Partial<T>[]) => T',
  en: 'Folds partial records from left to right using `merge`.',
  vi: 'Gộp các partial record từ trái sang phải bằng `merge`.',
  parameters: [parameter('sources', 'Partial<T>[]', 'Ordered partial source records.', 'Các partial record nguồn có thứ tự.')],
  returnsEn: 'The accumulated merged record, or an empty object when no sources are supplied.',
  returnsVi: 'Record merge tích lũy, hoặc object rỗng khi không truyền source.',
  throws: [commonErrors.validation, commonErrors.unsafeKey],
  runtimeEn: ['Each fold uses the default 1,000-level traversal bound from `merge`.'],
  runtimeVi: ['Mỗi lần gộp dùng giới hạn duyệt mặc định 1.000 cấp của `merge`.'],
  securityEn: ['The same own-property and prototype-pollution defenses as `merge` apply.'],
  securityVi: ['Áp dụng cùng cơ chế bảo vệ own-property và prototype pollution như `merge`.'],
  exampleIds: ['safe-objects', 'typed-errors'],
} as const satisfies MemberSpec;

const fetchAllByPagingSpec = {
  name: 'fetchAllByPaging',
  signature: '<T = unknown>(func: (pageSize: number, pageNumber: number, signal?: AbortSignal) => Promise<{ items: T[]; total: number; }>, defaultPageSize?: number, options?: FetchAllByPagingOptions) => Promise<T[]>',
  en: 'Exhausts a strictly zero-based paginated endpoint and returns all items in order.',
  vi: 'Duyệt hết endpoint phân trang bắt buộc zero-based và trả mọi phần tử đúng thứ tự.',
  parameters: [
    parameter('func', '(pageSize: number, pageNumber: number, signal?: AbortSignal) => Promise<{ items: T[]; total: number }>', 'Page loader. The first `pageNumber` is always `0`, followed by consecutive safe integers.', 'Hàm tải trang. `pageNumber` đầu tiên luôn là `0`, sau đó là các số nguyên an toàn liên tiếp.'),
    parameter('defaultPageSize', 'number', 'Positive safe-integer page size.', 'Kích thước trang là số nguyên an toàn dương.', { optional: true, defaultValue: '1000' }),
    parameter('options', 'FetchAllByPagingOptions', 'Abort, page-cap, and total-change policies.', 'Chính sách hủy, giới hạn trang và thay đổi total.', { optional: true, defaultValue: '{}' }),
  ],
  returnsEn: 'A promise for all page items accumulated in request order.',
  returnsVi: 'Promise trả mọi phần tử được tích lũy theo thứ tự request.',
  throws: [commonErrors.validation, commonErrors.pagingResponse, commonErrors.pagingLimit],
  runtimeEn: [
    'Every call starts at page 0. There is no public page-base or resume-page option.',
    'Each response validates `items`, non-negative safe-integer `total`, page size, empty-page progress, total consistency, and accumulation bounds; equal item values across offsets are preserved.',
    'For a one-based transport, adapt only inside the callback, for example `api.list({ page: pageNumber + 1, size: pageSize, signal })`.',
  ],
  runtimeVi: [
    'Mọi lần gọi đều bắt đầu từ trang 0. Không có option công khai đổi page base hoặc tiếp tục từ trang khác.',
    'Mỗi response kiểm tra `items`, `total` là số nguyên an toàn không âm, kích thước trang, tiến triển của trang rỗng, tính nhất quán total và giới hạn tích lũy; giá trị giống nhau ở các offset vẫn được giữ.',
    'Với transport one-based, chỉ chuyển đổi bên trong callback, ví dụ `api.list({ page: pageNumber + 1, size: pageSize, signal })`.',
  ],
  securityEn: ['`maxPages` defaults to 10,000 and bounds non-terminating endpoints; abort is raced against each pending page request.'],
  securityVi: ['`maxPages` mặc định 10.000 để giới hạn endpoint không kết thúc; tín hiệu hủy được race với từng request trang đang chờ.'],
  exampleIds: ['paging-zero', 'paging-one-based', 'typed-errors'],
} as const satisfies MemberSpec;

const randomIdSpec = {
  name: 'randomId',
  signature: '(prefix?: string | null) => string',
  en: 'Generates a short time-and-random identifier with an optional prefix.',
  vi: 'Tạo định danh ngắn từ thời gian và số ngẫu nhiên với tiền tố tùy chọn.',
  parameters: [parameter('prefix', 'string | null', 'Optional prefix separated with `_` when truthy.', 'Tiền tố tùy chọn, được ngăn bằng `_` khi có giá trị truthy.', { optional: true, defaultValue: 'undefined' })],
  returnsEn: 'A non-empty convenience identifier string.',
  returnsVi: 'Chuỗi định danh tiện ích không rỗng.',
  runtimeEn: ['Uses `Date.now()` and `Math.random()`.'],
  runtimeVi: ['Dùng `Date.now()` và `Math.random()`.'],
  securityEn: ['Not a UUID and not cryptographically secure; use `generateUuid` when secure uniqueness is required.'],
  securityVi: ['Không phải UUID và không an toàn mật mã; dùng `generateUuid` khi cần tính duy nhất an toàn.'],
  exampleIds: ['numbers-validation'],
} as const satisfies MemberSpec;

const generateUuidSpec = {
  name: 'generateUuid',
  signature: '() => string',
  en: 'Generates a lowercase RFC-compatible UUID v4 using cryptographically secure randomness.',
  vi: 'Tạo UUID v4 chữ thường tương thích RFC bằng nguồn ngẫu nhiên an toàn mật mã.',
  parameters: [],
  returnsEn: 'A lowercase UUID v4 with RFC variant bits.',
  returnsVi: 'UUID v4 chữ thường có các bit variant theo RFC.',
  throws: [commonErrors.secureRandom],
  runtimeEn: ['Uses `crypto.randomUUID()` when valid, then securely falls back to `crypto.getRandomValues()` if available.'],
  runtimeVi: ['Dùng `crypto.randomUUID()` khi hợp lệ, rồi fallback an toàn sang `crypto.getRandomValues()` nếu có.'],
  securityEn: ['There is no `Math.random()` or timestamp fallback; absence or failure of secure randomness throws.'],
  securityVi: ['Không có fallback `Math.random()` hay timestamp; thiếu hoặc lỗi nguồn ngẫu nhiên an toàn sẽ ném lỗi.'],
  exampleIds: ['typed-errors'],
} as const satisfies MemberSpec;

const objectMemberSpecs = [
  stableStringifySpec,
  canonicalStringifySpec,
  hashSpec,
  hash32Spec,
  sha256CanonicalSpec,
  sha256BlobSpec,
  parseQueryParamsSpec,
  getNestedValueSpec,
  isPlainObjectSpec,
  cloneSpec,
  mergeSpec,
  deepMergeSpec,
] as const satisfies readonly MemberSpec[];

const utilityMemberSpecs = [
  fetchAllByPagingSpec,
  randomIdSpec,
  stableStringifySpec,
  canonicalStringifySpec,
  hashSpec,
  hash32Spec,
  sha256CanonicalSpec,
  sha256BlobSpec,
  parseQueryParamsSpec,
  generateUuidSpec,
  getNestedValueSpec,
  isPlainObjectSpec,
  cloneSpec,
  mergeSpec,
  deepMergeSpec,
] as const satisfies readonly MemberSpec[];

const syntaxOnlySecurityEn = ['Syntax checks do not verify ownership, identity, reachability, content safety, or authorization.'] as const;
const syntaxOnlySecurityVi = ['Kiểm tra cú pháp không xác minh quyền sở hữu, danh tính, khả năng truy cập, độ an toàn nội dung hay phân quyền.'] as const;

const syntaxMember = (
  name: string,
  en: string,
  vi: string,
  acceptedEn: string,
  acceptedVi: string,
  extras: Partial<Omit<MemberSpec, 'name' | 'signature' | 'en' | 'vi' | 'parameters' | 'returnsEn' | 'returnsVi'>> = {},
): MemberSpec => ({
  name,
  signature: '(value: unknown) => boolean',
  en,
  vi,
  parameters: [valueParameter],
  returnsEn: `\`true\` ${acceptedEn}; otherwise \`false\`.`,
  returnsVi: `\`true\` ${acceptedVi}; ngược lại là \`false\`.`,
  runtimeEn: ['`null`, `undefined`, and the empty string return `false`.'],
  runtimeVi: ['`null`, `undefined` và chuỗi rỗng trả về `false`.'],
  securityEn: syntaxOnlySecurityEn,
  securityVi: syntaxOnlySecurityVi,
  exampleIds: ['numbers-validation'],
  ...extras,
});

const validationMemberSpecs = [
  {
    name: 'validate',
    signature: '(type: ValidationPatternType, value: unknown) => boolean',
    en: 'Validates a value against one named built-in pattern.',
    vi: 'Xác thực một giá trị theo pattern built-in được chỉ định.',
    parameters: [
      parameter('type', 'ValidationPatternType', 'Supported built-in pattern identifier.', 'Định danh pattern built-in được hỗ trợ.'),
      valueParameter,
    ],
    returnsEn: '`true` when the value satisfies the selected syntax policy; otherwise `false`.',
    returnsVi: '`true` khi giá trị thỏa chính sách cú pháp đã chọn; ngược lại là `false`.',
    throws: [commonErrors.validation],
    runtimeEn: ['URL, image URL, UUID, and Base64 route through their dedicated strict helpers; an unknown runtime type throws.'],
    runtimeVi: ['URL, image URL, UUID và Base64 được chuyển qua helper nghiêm ngặt tương ứng; type runtime không biết sẽ ném lỗi.'],
    securityEn: syntaxOnlySecurityEn,
    securityVi: syntaxOnlySecurityVi,
    exampleIds: ['numbers-validation', 'typed-errors'],
  },
  syntaxMember('isEmail', 'Checks the built-in email-address syntax.', 'Kiểm tra cú pháp địa chỉ email built-in.', 'when the value matches the email pattern', 'khi giá trị khớp pattern email'),
  syntaxMember('isPhone', 'Checks the generic international phone-number syntax.', 'Kiểm tra cú pháp số điện thoại quốc tế tổng quát.', 'when the value matches the generic phone pattern', 'khi giá trị khớp pattern điện thoại tổng quát'),
  syntaxMember('isVnPhone', 'Checks Vietnamese mobile-number syntax, including supported `+84` form.', 'Kiểm tra cú pháp số di động Việt Nam, gồm dạng `+84` được hỗ trợ.', 'when the value matches a supported Vietnamese mobile prefix and length', 'khi giá trị khớp đầu số và độ dài di động Việt Nam được hỗ trợ'),
  syntaxMember('isVnId', 'Checks the 12-digit Vietnamese national-ID syntax.', 'Kiểm tra cú pháp CCCD Việt Nam gồm 12 chữ số.', 'for exactly 12 decimal digits', 'với đúng 12 chữ số thập phân'),
  syntaxMember('isPassport', 'Checks the built-in passport syntax of one uppercase letter followed by seven digits.', 'Kiểm tra cú pháp hộ chiếu built-in gồm một chữ in hoa theo sau bởi bảy chữ số.', 'when the passport pattern matches', 'khi khớp pattern hộ chiếu'),
  syntaxMember('isVnIdOrPassport', 'Checks either Vietnamese national-ID or passport syntax.', 'Kiểm tra cú pháp CCCD Việt Nam hoặc hộ chiếu.', 'when either supported identifier pattern matches', 'khi một trong hai pattern định danh được hỗ trợ khớp'),
  syntaxMember('isTime', 'Checks 24-hour `HH:mm` time syntax.', 'Kiểm tra cú pháp thời gian 24 giờ `HH:mm`.', 'for a time from `00:00` through `23:59`', 'với thời gian từ `00:00` đến `23:59`'),
  {
    name: 'isUrl',
    signature: '(value: unknown, options?: UrlValidationOptions) => boolean',
    en: 'Parses a URL and applies explicit protocol, relative-path, credential, and host policy.',
    vi: 'Phân tích URL và áp dụng chính sách tường minh về protocol, đường dẫn tương đối, credential và host.',
    parameters: [
      valueParameter,
      parameter('options', 'UrlValidationOptions', 'URL syntax and policy options.', 'Tùy chọn cú pháp và chính sách URL.', { optional: true, defaultValue: '{}' }),
    ],
    returnsEn: '`true` when parsing succeeds and every configured policy is satisfied.',
    returnsVi: '`true` khi phân tích thành công và thỏa mọi chính sách đã cấu hình.',
    runtimeEn: ['Defaults to absolute HTTP/HTTPS URLs, no embedded credentials, and a required host. Relative parsing uses `http://localhost` only as a parsing base.'],
    runtimeVi: ['Mặc định chỉ URL HTTP/HTTPS tuyệt đối, không credential nhúng và bắt buộc có host. Phân tích đường dẫn tương đối chỉ dùng `http://localhost` làm base parser.'],
    securityEn: ['A syntactically allowed URL can still target private networks, redirects, or hostile content; enforce SSRF and fetch policy at the trusted network boundary.'],
    securityVi: ['URL hợp lệ cú pháp vẫn có thể trỏ tới mạng riêng, redirect hoặc nội dung độc hại; áp dụng chính sách SSRF và fetch tại ranh giới mạng tin cậy.'],
    exampleIds: ['numbers-validation'],
  },
  syntaxMember('isDomain', 'Checks bare domain-name syntax.', 'Kiểm tra cú pháp tên miền trần.', 'when a multi-label domain pattern matches', 'khi khớp pattern domain nhiều nhãn'),
  syntaxMember('isIpv4', 'Checks dotted-decimal IPv4 syntax and octet bounds.', 'Kiểm tra cú pháp IPv4 thập phân dấu chấm và giới hạn octet.', 'when all four decimal octets are valid', 'khi cả bốn octet thập phân hợp lệ'),
  syntaxMember('isIpv6', 'Checks the built-in IPv6 textual syntax.', 'Kiểm tra cú pháp văn bản IPv6 built-in.', 'when the supported IPv6 pattern matches', 'khi khớp pattern IPv6 được hỗ trợ'),
  syntaxMember(
    'isImageUrl',
    'Checks legacy HTTP(S)-URL-plus-image-extension syntax.',
    'Kiểm tra cú pháp cũ gồm URL HTTP(S) và phần mở rộng ảnh.',
    'when both strict default URL policy and a known image filename extension match',
    'khi vừa thỏa chính sách URL mặc định nghiêm ngặt vừa có phần mở rộng tên file ảnh đã biết',
    {
      runtimeEn: ['Retains the v1.x absolute HTTP(S) URL plus extension role, while the v1.2 URL parser rejects credentials and malformed values more strictly.'],
      runtimeVi: ['Giữ vai trò v1.x: URL HTTP(S) tuyệt đối cộng phần mở rộng, nhưng parser URL v1.2 từ chối credential và giá trị sai nghiêm ngặt hơn.'],
      securityEn: ['Filename syntax does not prove that downloaded bytes are an image; validate trusted-server response type and content separately.'],
      securityVi: ['Cú pháp tên file không chứng minh byte tải về là ảnh; xác thực riêng loại response và nội dung tại server tin cậy.'],
      deprecation: deprecated(
        'hasImageFileExtension',
        'Use `hasImageFileExtension` for filename syntax and call `isUrl` separately when URL policy is required; the replacement can accept relative filenames.',
        'Dùng `hasImageFileExtension` cho cú pháp tên file và gọi riêng `isUrl` khi cần chính sách URL; hàm thay thế có thể chấp nhận tên file tương đối.',
      ),
    },
  ),
  syntaxMember(
    'hasImageFileExtension',
    'Checks whether a filename or path ends with a known image extension.',
    'Kiểm tra tên file hoặc đường dẫn có kết thúc bằng phần mở rộng ảnh đã biết hay không.',
    'for jpeg, jpg, png, gif, webp, svg, or bmp after ignoring query and fragment suffixes',
    'với jpeg, jpg, png, gif, webp, svg hoặc bmp sau khi bỏ hậu tố query và fragment',
    {
      runtimeEn: ['Accepts relative paths and does not parse or require a URL.'],
      runtimeVi: ['Chấp nhận đường dẫn tương đối và không phân tích hay yêu cầu URL.'],
      securityEn: ['An extension is metadata only; inspect downloaded bytes and enforce upload policy on a trusted server.'],
      securityVi: ['Phần mở rộng chỉ là metadata; kiểm tra byte tải về và áp dụng chính sách upload trên server tin cậy.'],
    },
  ),
  syntaxMember('isSlug', 'Checks lowercase URL-slug syntax.', 'Kiểm tra cú pháp URL slug chữ thường.', 'for lowercase alphanumeric segments separated by single hyphens', 'với các segment chữ thường/chữ số được ngăn bằng một dấu gạch ngang'),
  syntaxMember(
    'isNumber',
    'Checks the legacy decimal-number string pattern.',
    'Kiểm tra pattern chuỗi số thập phân kiểu cũ.',
    'when the legacy integer-or-decimal syntax matches',
    'khi khớp cú pháp số nguyên hoặc thập phân kiểu cũ',
    {
      deprecation: deprecated(
        'isNumericString',
        'Use `isNumericString` for explicit exponent, hexadecimal, sign, and whitespace options.',
        'Dùng `isNumericString` để cấu hình tường minh số mũ, hệ 16, dấu và khoảng trắng.',
      ),
    },
  ),
  syntaxMember('isInteger', 'Checks signed decimal-integer string syntax.', 'Kiểm tra cú pháp chuỗi số nguyên thập phân có dấu.', 'when the integer pattern matches', 'khi khớp pattern số nguyên'),
  syntaxMember('isDecimal', 'Checks signed decimal syntax that requires a decimal point.', 'Kiểm tra cú pháp số thập phân có dấu và bắt buộc có dấu chấm.', 'when the decimal-point pattern matches', 'khi khớp pattern có dấu chấm thập phân'),
  syntaxMember('isPositiveNumber', 'Checks the built-in non-negative integer-or-decimal syntax.', 'Kiểm tra cú pháp số nguyên hoặc thập phân không âm built-in.', 'when the non-negative numeric pattern matches, including zero', 'khi khớp pattern số không âm, gồm cả số 0'),
  {
    name: 'isFiniteNumber',
    signature: '(value: unknown) => value is number',
    en: 'Checks for a primitive finite JavaScript number without coercion.',
    vi: 'Kiểm tra number primitive hữu hạn của JavaScript mà không ép kiểu.',
    parameters: [valueParameter],
    returnsEn: '`true` only for a primitive number other than `NaN`, `Infinity`, or `-Infinity`.',
    returnsVi: '`true` chỉ với number primitive khác `NaN`, `Infinity` và `-Infinity`.',
    runtimeEn: ['Numeric strings return `false`.'],
    runtimeVi: ['Chuỗi số trả về `false`.'],
    securityEn: ['Finite-number validation does not enforce an application-specific range or unit.'],
    securityVi: ['Xác thực số hữu hạn không áp dụng miền giá trị hay đơn vị riêng của ứng dụng.'],
    exampleIds: ['numbers-validation'],
  },
  {
    name: 'isNumericString',
    signature: '(value: unknown, options?: NumericStringOptions) => value is string',
    en: 'Checks numeric-string syntax under explicit sign, decimal, exponent, hexadecimal, and whitespace policy.',
    vi: 'Kiểm tra cú pháp chuỗi số theo chính sách tường minh về dấu, thập phân, số mũ, hệ 16 và khoảng trắng.',
    parameters: [
      valueParameter,
      parameter('options', 'NumericStringOptions', 'Explicit numeric syntax policy.', 'Chính sách cú pháp số tường minh.', { optional: true, defaultValue: '{}' }),
    ],
    returnsEn: '`true` only for a string accepted by the configured syntax policy.',
    returnsVi: '`true` chỉ với chuỗi được chính sách cú pháp đã cấu hình chấp nhận.',
    runtimeEn: ['Does not coerce non-string values.'],
    runtimeVi: ['Không ép kiểu giá trị không phải chuỗi.'],
    securityEn: ['Syntax acceptance does not impose business range, precision, currency, or unit constraints.'],
    securityVi: ['Chấp nhận cú pháp không áp dụng giới hạn nghiệp vụ về miền, độ chính xác, tiền tệ hay đơn vị.'],
    exampleIds: ['numbers-validation'],
  },
  {
    name: 'parseFiniteNumber',
    signature: '(value: unknown, options?: ParseFiniteNumberOptions) => number | null',
    en: 'Parses a finite number under explicit coercion and numeric-string policy.',
    vi: 'Phân tích số hữu hạn theo chính sách ép kiểu và chuỗi số tường minh.',
    parameters: [
      valueParameter,
      parameter('options', 'ParseFiniteNumberOptions', 'Explicit parsing and syntax policy.', 'Chính sách phân tích và cú pháp tường minh.', { optional: true, defaultValue: '{}' }),
    ],
    returnsEn: 'A primitive finite number, or `null` when input is rejected.',
    returnsVi: 'Number primitive hữu hạn, hoặc `null` khi input bị từ chối.',
    runtimeEn: ['Accepted coercions are controlled by `ParseFiniteNumberOptions`; invalid and non-finite results return `null`.'],
    runtimeVi: ['Phép ép kiểu được chấp nhận do `ParseFiniteNumberOptions` kiểm soát; kết quả sai hoặc không hữu hạn trả về `null`.'],
    securityEn: ['Apply domain-specific range and precision checks after parsing.'],
    securityVi: ['Áp dụng kiểm tra miền và độ chính xác riêng của nghiệp vụ sau khi phân tích.'],
    exampleIds: ['numbers-validation'],
  },
  {
    name: 'isUuid',
    signature: '(value: unknown, options?: UuidValidationOptions) => boolean',
    en: 'Validates generic hyphenated UUID syntax with optional version, variant, and casing policy.',
    vi: 'Xác thực cú pháp UUID có dấu gạch nối tổng quát với chính sách tùy chọn về version, variant và hoa/thường.',
    parameters: [
      valueParameter,
      parameter('options', 'UuidValidationOptions', 'Optional version, RFC-variant, and uppercase policy.', 'Chính sách tùy chọn về version, RFC variant và chữ hoa.', { optional: true, defaultValue: '{}' }),
    ],
    returnsEn: '`true` for generic UUID shape satisfying every requested option; the default does not require v4 or RFC variant bits.',
    returnsVi: '`true` với cấu trúc UUID tổng quát thỏa mọi option; mặc định không bắt buộc v4 hay bit variant RFC.',
    runtimeEn: ['Supports version nibble checks for versions 1 through 8. Uppercase is allowed by default.'],
    runtimeVi: ['Hỗ trợ kiểm tra nibble version từ 1 đến 8. Mặc định cho phép chữ hoa.'],
    securityEn: ['Use `isUuidV4` when the contract specifically requires RFC-compatible version 4; UUID syntax does not prove origin or authorization.'],
    securityVi: ['Dùng `isUuidV4` khi contract yêu cầu cụ thể version 4 tương thích RFC; cú pháp UUID không chứng minh nguồn gốc hay phân quyền.'],
    exampleIds: ['numbers-validation'],
  },
  {
    name: 'isUuidV4',
    signature: '(value: unknown) => boolean',
    en: 'Validates UUID version 4 syntax and RFC variant bits.',
    vi: 'Xác thực cú pháp UUID version 4 và các bit variant RFC.',
    parameters: [valueParameter],
    returnsEn: '`true` only for a hyphenated v4 UUID with an RFC variant nibble.',
    returnsVi: '`true` chỉ với UUID v4 có dấu gạch nối và nibble variant RFC.',
    runtimeEn: ['Equivalent to `isUuid(value, { version: 4, requireRfcVariant: true })`.'],
    runtimeVi: ['Tương đương `isUuid(value, { version: 4, requireRfcVariant: true })`.'],
    securityEn: ['Validation checks shape, not whether randomness was generated securely; use `generateUuid` for secure local generation.'],
    securityVi: ['Xác thực chỉ kiểm tra cấu trúc, không chứng minh nguồn ngẫu nhiên an toàn; dùng `generateUuid` để sinh local an toàn.'],
    exampleIds: ['numbers-validation'],
  },
  syntaxMember('isCode16', 'Checks exactly 16 alphanumeric characters.', 'Kiểm tra đúng 16 ký tự chữ-số.', 'for exactly 16 ASCII letters or digits', 'với đúng 16 chữ cái ASCII hoặc chữ số'),
  syntaxMember('isCode32', 'Checks exactly 32 alphanumeric characters.', 'Kiểm tra đúng 32 ký tự chữ-số.', 'for exactly 32 ASCII letters or digits', 'với đúng 32 chữ cái ASCII hoặc chữ số'),
  syntaxMember('isHexColor', 'Checks CSS-style three- or six-digit hexadecimal color syntax.', 'Kiểm tra cú pháp màu hex CSS ba hoặc sáu chữ số.', 'for `#RGB` or `#RRGGBB` syntax', 'với cú pháp `#RGB` hoặc `#RRGGBB`'),
  syntaxMember('isBase64', 'Checks standard Base64 text syntax with canonical padding when required.', 'Kiểm tra cú pháp văn bản Base64 chuẩn với padding canonical khi cần.', 'when the standard Base64 pattern matches', 'khi khớp pattern Base64 chuẩn'),
  syntaxMember('isCode', 'Checks the legacy 2–20 character application-code syntax.', 'Kiểm tra cú pháp code ứng dụng kiểu cũ dài 2–20 ký tự.', 'for ASCII letters, digits, `@`, `_`, or `-` within the length bound', 'với chữ cái ASCII, chữ số, `@`, `_` hoặc `-` trong giới hạn độ dài'),
] as const satisfies readonly MemberSpec[];

const filterMembers = filterMemberSpecs.map(spec => createMember('FilterUtilities', spec));
const objectMembers = objectMemberSpecs.map(spec => createMember('ObjectUtilities', spec));
const utilityMembers = utilityMemberSpecs.map(spec => createMember('Utilities', spec));
const validationMembers = validationMemberSpecs.map(spec => createMember('ValidationUtilities', spec));

const entryFromMember = (pageId: PageId, spec: MemberSpec): ApiEntry => createEntry({
  symbol: spec.name,
  kind: 'function',
  pageId,
  importPath: FNS_IMPORT,
  signature: spec.signature,
  en: spec.en ?? `${spec.name} function.`,
  vi: spec.vi ?? `Hàm ${spec.name}.`,
  returnsEn: spec.returnsEn,
  returnsVi: spec.returnsVi,
  parameters: spec.parameters,
  throws: spec.throws,
  runtimeEn: spec.runtimeEn,
  runtimeVi: spec.runtimeVi,
  securityEn: spec.securityEn,
  securityVi: spec.securityVi,
  exampleIds: spec.exampleIds,
  deprecation: spec.deprecation,
});

const namespaceEntry = (
  symbol: 'FilterUtilities' | 'ObjectUtilities' | 'Utilities' | 'ValidationUtilities',
  pageId: PageId,
  signature: string,
  en: string,
  vi: string,
  members: readonly ApiMember[],
  exampleIds: readonly string[],
  securityEn: readonly string[],
  securityVi: readonly string[],
): ApiEntry => createEntry({
  symbol,
  kind: 'namespace',
  pageId,
  importPath: FNS_IMPORT,
  signature,
  en,
  vi,
  returnsEn: `A utility object exposing ${members.length} documented functions.`,
  returnsVi: `Object tiện ích cung cấp ${members.length} hàm đã được tài liệu hóa.`,
  runtimeEn: ['Importing the namespace does not add runtime dependencies beyond the library and platform APIs used by the called member.'],
  runtimeVi: ['Import namespace không thêm dependency runtime ngoài thư viện và platform API mà member được gọi sử dụng.'],
  securityEn,
  securityVi,
  exampleIds,
}, members);

const filterNamespaceEntry = namespaceEntry(
  'FilterUtilities',
  'api-filter',
  'const FilterUtilities: { match: <T = unknown>(filters: Filter<T>[], item: T, options?: MatchOptions<T>) => boolean; evaluate: <T = unknown>(filter: Filter<T>, item: T, options?: MatchOptions<T>) => boolean; evaluateFilter: <T = unknown>(item: T, filter: unknown, options?: MatchOptions<T>) => boolean; validateFilter: <T = unknown>(filter: unknown, options?: MatchOptions<T>) => ValidatedFilter<T>; resolveData: (filter: FilterHasData, entity: unknown, options?: MatchOptions) => unknown; resolveRelativeDate: (relative: DateRelative, now?: Date) => Date; toEpoch: (value: unknown, options?: ToEpochOptions) => number | null; relativeDate: (amount: number, direction: DateRelative["direction"], unit: DateRelative["unit"]) => DateRelative; isDateRelative: (value: unknown) => value is DateRelative; }',
  'Strict validation, date normalization, operand resolution, and client-side filter evaluation helpers.',
  'Các helper xác thực nghiêm ngặt, chuẩn hóa ngày, phân giải toán hạng và đánh giá bộ lọc phía client.',
  filterMembers,
  ['strict-filters', 'typed-errors'],
  filterSecurityEn,
  filterSecurityVi,
);

const objectNamespaceEntry = namespaceEntry(
  'ObjectUtilities',
  'api-object-utility-serialization',
  'const ObjectUtilities: { stableStringify: (value: unknown, options?: StableStringifyOptions) => string; canonicalStringify: (value: unknown, options?: CanonicalStringifyOptions) => string; hash: (value: unknown) => string; hash32: (value: unknown) => string; sha256Canonical: (value: unknown, options?: CanonicalStringifyOptions) => Promise<string>; sha256Blob: (blob: Blob) => Promise<string>; parseQueryParams: (queryString?: string) => Record<string, string>; getNestedValue: <T = unknown>(obj: unknown, path: string, options?: PropertyPathOptions) => T | undefined; isPlainObject: (value: unknown) => value is PlainRecord; clone: <T>(value: T, options?: ObjectTraversalOptions) => T; merge: <T>(defaultValue: T, overrideValue: T | undefined, options?: ObjectTraversalOptions) => T; deepMerge: <T>(...sources: Partial<T>[]) => T; }',
  'Object-focused deterministic serialization, hashing, safe traversal, cloning, and merge helpers.',
  'Các helper tập trung vào object: tuần tự hóa xác định, hash, duyệt an toàn, clone và merge.',
  objectMembers,
  ['safe-objects', 'canonical-hashing', 'typed-errors'],
  ['Own-property traversal, accessor rejection, depth bounds, and prototype-sensitive key checks apply where relevant.', 'Choose SHA-256 helpers rather than `hash`/`hash32` for collision-resistant use cases.'],
  ['Áp dụng duyệt own-property, từ chối accessor, giới hạn độ sâu và kiểm tra khóa nhạy cảm với prototype khi phù hợp.', 'Chọn helper SHA-256 thay vì `hash`/`hash32` cho trường hợp cần chống va chạm.'],
);

const utilitiesNamespaceEntry = namespaceEntry(
  'Utilities',
  'api-object-utility-serialization',
  'const Utilities: { fetchAllByPaging: <T = unknown>(func: (pageSize: number, pageNumber: number, signal?: AbortSignal) => Promise<{ items: T[]; total: number; }>, defaultPageSize?: number, options?: FetchAllByPagingOptions) => Promise<T[]>; randomId: (prefix?: string | null) => string; stableStringify: (value: unknown, options?: StableStringifyOptions) => string; canonicalStringify: (value: unknown, options?: CanonicalStringifyOptions) => string; hash: (value: unknown) => string; hash32: (value: unknown) => string; sha256Canonical: (value: unknown, options?: CanonicalStringifyOptions) => Promise<string>; sha256Blob: (blob: Blob) => Promise<string>; parseQueryParams: (queryString?: string) => Record<string, string>; generateUuid: () => string; getNestedValue: <T = unknown>(obj: unknown, path: string, options?: PropertyPathOptions) => T | undefined; isPlainObject: (value: unknown) => value is PlainRecord; clone: <T>(value: T, options?: ObjectTraversalOptions) => T; merge: <T>(defaultValue: T, overrideValue: T | undefined, options?: ObjectTraversalOptions) => T; deepMerge: <T>(...sources: Partial<T>[]) => T; }',
  'General pagination, identifiers, serialization, hashing, query parsing, and safe object utilities.',
  'Tiện ích tổng quát cho phân trang, định danh, tuần tự hóa, hash, phân tích query và object an toàn.',
  utilityMembers,
  ['paging-zero', 'paging-one-based', 'safe-objects', 'canonical-hashing', 'typed-errors'],
  ['Pagination is strictly zero-based; one-based conversion belongs only inside the transport callback.', 'Security-sensitive identifiers require `generateUuid`; security-sensitive hashes require SHA-256, never `randomId` or `hash32`.'],
  ['Phân trang bắt buộc zero-based; chuyển đổi one-based chỉ thuộc callback transport.', 'Định danh nhạy cảm bảo mật phải dùng `generateUuid`; hash nhạy cảm bảo mật phải dùng SHA-256, không dùng `randomId` hay `hash32`.'],
);

const validationNamespaceEntry = namespaceEntry(
  'ValidationUtilities',
  'api-validation-async',
  'const ValidationUtilities: { validate: (type: ValidationPatternType, value: unknown) => boolean; isEmail: (value: unknown) => boolean; isPhone: (value: unknown) => boolean; isVnPhone: (value: unknown) => boolean; isVnId: (value: unknown) => boolean; isPassport: (value: unknown) => boolean; isVnIdOrPassport: (value: unknown) => boolean; isTime: (value: unknown) => boolean; isUrl: (value: unknown, options?: UrlValidationOptions) => boolean; isDomain: (value: unknown) => boolean; isIpv4: (value: unknown) => boolean; isIpv6: (value: unknown) => boolean; isImageUrl: (value: unknown) => boolean; hasImageFileExtension: (value: unknown) => boolean; isSlug: (value: unknown) => boolean; isNumber: (value: unknown) => boolean; isInteger: (value: unknown) => boolean; isDecimal: (value: unknown) => boolean; isPositiveNumber: (value: unknown) => boolean; isFiniteNumber: (value: unknown) => value is number; isNumericString: (value: unknown, options?: NumericStringOptions) => value is string; parseFiniteNumber: (value: unknown, options?: ParseFiniteNumberOptions) => number | null; isUuid: (value: unknown, options?: UuidValidationOptions) => boolean; isUuidV4: (value: unknown) => boolean; isCode16: (value: unknown) => boolean; isCode32: (value: unknown) => boolean; isHexColor: (value: unknown) => boolean; isBase64: (value: unknown) => boolean; isCode: (value: unknown) => boolean; }',
  'Named-pattern and explicit-policy syntax validation helpers.',
  'Các helper xác thực cú pháp theo pattern có tên và chính sách tường minh.',
  validationMembers,
  ['numbers-validation', 'typed-errors'],
  ['Validation is syntactic and deterministic; it does not establish identity, trust, authorization, remote content type, or network safety.', '`isUuid` checks generic UUID syntax by default; use `isUuidV4` for an RFC-compatible v4 contract.'],
  ['Xác thực chỉ kiểm tra cú pháp xác định; không thiết lập danh tính, độ tin cậy, phân quyền, loại nội dung từ xa hay an toàn mạng.', '`isUuid` mặc định kiểm tra cú pháp UUID tổng quát; dùng `isUuidV4` cho contract v4 tương thích RFC.'],
);

const toEpochOptionsEntry = createEntry({
  symbol: 'ToEpochOptions',
  kind: 'interface',
  pageId: 'api-filter',
  importPath: FNS_IMPORT,
  signature: 'interface ToEpochOptions { timestampUnit?: FilterTimestampUnit; legacyTimestampInference?: boolean; }',
  en: 'Controls how standalone numeric date values are converted to epoch milliseconds.',
  vi: 'Điều khiển cách giá trị ngày dạng số độc lập được chuyển sang epoch mili giây.',
  parameters: [
    parameter('timestampUnit', 'FilterTimestampUnit', 'Required unit for numeric timestamps unless legacy inference is enabled.', 'Đơn vị bắt buộc cho timestamp dạng số trừ khi bật suy đoán kiểu cũ.', { optional: true, defaultValue: 'undefined' }),
    parameter('legacyTimestampInference', 'boolean', 'Deprecated switch restoring the `< 1e12 = seconds` magnitude heuristic.', 'Công tắc deprecated khôi phục heuristic theo độ lớn `< 1e12 = giây`.', { optional: true, defaultValue: 'false' }),
  ],
  returnsEn: 'An options object consumed by `toEpoch`.',
  returnsVi: 'Object tùy chọn được `toEpoch` sử dụng.',
  runtimeEn: ['With neither option, numeric values and numeric strings resolve to `null`.'],
  runtimeVi: ['Khi không có cả hai option, số và chuỗi số được phân giải thành `null`.'],
  securityEn: ['Prefer explicit units because the deprecated magnitude heuristic is ambiguous.'],
  securityVi: ['Ưu tiên đơn vị tường minh vì heuristic theo độ lớn đã deprecated là mơ hồ.'],
  exampleIds: ['strict-filters'],
});

const serializationOptionsEntry = createEntry({
  symbol: 'SerializationOptions',
  kind: 'interface',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'interface SerializationOptions { maxDepth?: number; }',
  en: 'Shared traversal bound for deterministic serializers.',
  vi: 'Giới hạn duyệt dùng chung cho các bộ tuần tự hóa xác định.',
  parameters: [parameter('maxDepth', 'number', 'Maximum recursively visited depth; must be a positive safe integer.', 'Độ sâu đệ quy tối đa; phải là số nguyên an toàn dương.', { optional: true, defaultValue: '100' })],
  returnsEn: 'An options object accepted by deterministic serializers.',
  returnsVi: 'Object tùy chọn được các bộ tuần tự hóa xác định chấp nhận.',
  throws: [commonErrors.unsupported],
  runtimeEn: ['An invalid depth is rejected before traversal.'],
  runtimeVi: ['Độ sâu sai bị từ chối trước khi duyệt.'],
  securityEn: ['Keep a bounded depth for untrusted nested input.'],
  securityVi: ['Giữ giới hạn độ sâu cho input lồng nhau không tin cậy.'],
  exampleIds: ['canonical-hashing', 'typed-errors'],
});

const stableOptionsEntry = createEntry({
  symbol: 'StableStringifyOptions',
  kind: 'type',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'type StableStringifyOptions = SerializationOptions',
  en: 'Options alias for strict JSON-domain stable serialization.',
  vi: 'Alias tùy chọn cho tuần tự hóa ổn định miền JSON nghiêm ngặt.',
  parameters: [parameter('maxDepth', 'number', 'Maximum recursively visited depth.', 'Độ sâu đệ quy tối đa.', { optional: true, defaultValue: '100' })],
  returnsEn: 'The `SerializationOptions` shape.',
  returnsVi: 'Cấu trúc `SerializationOptions`.',
  runtimeEn: ['This is a type-only alias with no runtime value.'],
  runtimeVi: ['Đây là alias chỉ tồn tại ở type, không có giá trị runtime.'],
  securityEn: ['Use the depth bound when processing nested untrusted values.'],
  securityVi: ['Dùng giới hạn độ sâu khi xử lý giá trị lồng nhau không tin cậy.'],
  exampleIds: ['canonical-hashing'],
});

const canonicalOptionsEntry = createEntry({
  symbol: 'CanonicalStringifyOptions',
  kind: 'type',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'type CanonicalStringifyOptions = SerializationOptions',
  en: 'Options alias for extended type-tagged canonical serialization.',
  vi: 'Alias tùy chọn cho tuần tự hóa canonical mở rộng có type tag.',
  parameters: [parameter('maxDepth', 'number', 'Maximum recursively visited depth.', 'Độ sâu đệ quy tối đa.', { optional: true, defaultValue: '100' })],
  returnsEn: 'The `SerializationOptions` shape.',
  returnsVi: 'Cấu trúc `SerializationOptions`.',
  runtimeEn: ['This is a type-only alias with no runtime value.'],
  runtimeVi: ['Đây là alias chỉ tồn tại ở type, không có giá trị runtime.'],
  securityEn: ['Use the depth bound when processing nested untrusted values.'],
  securityVi: ['Dùng giới hạn độ sâu khi xử lý giá trị lồng nhau không tin cậy.'],
  exampleIds: ['canonical-hashing'],
});

const propertyPathOptionsEntry = createEntry({
  symbol: 'PropertyPathOptions',
  kind: 'interface',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'interface PropertyPathOptions { maxDepth?: number; allowAccessors?: boolean; }',
  en: 'Configures bounded own-property path traversal.',
  vi: 'Cấu hình duyệt đường dẫn own-property có giới hạn.',
  parameters: [
    parameter('maxDepth', 'number', 'Maximum number of parsed path segments.', 'Số segment đường dẫn tối đa được phân tích.', { optional: true, defaultValue: '32' }),
    parameter('allowAccessors', 'boolean', 'Whether own getter properties may be invoked.', 'Có cho phép gọi own getter property hay không.', { optional: true, defaultValue: 'false' }),
  ],
  returnsEn: 'An options object accepted by safe path helpers.',
  returnsVi: 'Object tùy chọn được helper đường dẫn an toàn sử dụng.',
  runtimeEn: ['Malformed paths and invalid depth values throw `UnsafePropertyPathError`.'],
  runtimeVi: ['Đường dẫn sai và độ sâu không hợp lệ ném `UnsafePropertyPathError`.'],
  securityEn: ['Leave `allowAccessors` disabled for untrusted graphs because getters can execute arbitrary side effects.'],
  securityVi: ['Giữ `allowAccessors` tắt với đồ thị không tin cậy vì getter có thể thực thi side effect tùy ý.'],
  exampleIds: ['safe-objects', 'typed-errors'],
});

const plainRecordEntry = createEntry({
  symbol: 'PlainRecord',
  kind: 'type',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'type PlainRecord = Record<string, unknown>',
  en: 'String-keyed unknown-value record type used by safe object helpers.',
  vi: 'Kiểu record khóa chuỗi, giá trị unknown được các helper object an toàn sử dụng.',
  returnsEn: 'A type alias for `Record<string, unknown>`.',
  returnsVi: 'Alias type của `Record<string, unknown>`.',
  runtimeEn: ['This alias has no runtime value; `isPlainObject` performs the runtime prototype check.'],
  runtimeVi: ['Alias này không có giá trị runtime; `isPlainObject` thực hiện kiểm tra prototype lúc chạy.'],
  securityEn: ['The TypeScript type alone does not prove that a runtime value has safe keys or a plain prototype.'],
  securityVi: ['Kiểu TypeScript tự nó không chứng minh giá trị runtime có khóa an toàn hay plain prototype.'],
  exampleIds: ['safe-objects'],
});

const traversalOptionsEntry = createEntry({
  symbol: 'ObjectTraversalOptions',
  kind: 'interface',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'interface ObjectTraversalOptions { maxDepth?: number; }',
  en: 'Bounds recursive clone and merge traversal.',
  vi: 'Giới hạn phép duyệt đệ quy khi clone và merge.',
  parameters: [parameter('maxDepth', 'number', 'Maximum nested object/array depth; must be a positive safe integer.', 'Độ sâu object/array lồng nhau tối đa; phải là số nguyên an toàn dương.', { optional: true, defaultValue: '1000' })],
  returnsEn: 'An options object consumed by `clone` and `merge`.',
  returnsVi: 'Object tùy chọn được `clone` và `merge` sử dụng.',
  throws: [commonErrors.validation],
  runtimeEn: ['Traversal beyond the configured limit throws rather than overflowing the stack.'],
  runtimeVi: ['Duyệt vượt giới hạn cấu hình sẽ ném lỗi thay vì tràn stack.'],
  securityEn: ['Choose a lower limit for attacker-controlled deeply nested graphs when appropriate.'],
  securityVi: ['Chọn giới hạn thấp hơn khi phù hợp với đồ thị lồng sâu do attacker kiểm soát.'],
  exampleIds: ['safe-objects', 'typed-errors'],
});

const pagingOptionsEntry = createEntry({
  symbol: 'FetchAllByPagingOptions',
  kind: 'interface',
  pageId: 'api-object-utility-serialization',
  importPath: FNS_IMPORT,
  signature: 'interface FetchAllByPagingOptions { maxPages?: number; signal?: AbortSignal; totalChangePolicy?: "error" | "latest"; }',
  en: 'Controls bounded zero-based pagination, cancellation, and changing totals.',
  vi: 'Điều khiển phân trang zero-based có giới hạn, hủy và total thay đổi.',
  parameters: [
    parameter('maxPages', 'number', 'Hard cap on fetched pages; must be a positive safe integer.', 'Giới hạn cứng số trang tải; phải là số nguyên an toàn dương.', { optional: true, defaultValue: '10000' }),
    parameter('signal', 'AbortSignal', 'Cancellation signal raced against and forwarded to each page request.', 'Tín hiệu hủy được race với và truyền vào từng request trang.', { optional: true, defaultValue: 'undefined' }),
    parameter('totalChangePolicy', '"error" | "latest"', 'How a changed response total is handled after page 0.', 'Cách xử lý total response thay đổi sau trang 0.', { optional: true, defaultValue: '"error"' }),
  ],
  returnsEn: 'An options object consumed by `fetchAllByPaging`.',
  returnsVi: 'Object tùy chọn được `fetchAllByPaging` sử dụng.',
  runtimeEn: ['There is intentionally no page-base or initial-page option: the callback always starts at page 0.'],
  runtimeVi: ['Cố ý không có option page base hay initial page: callback luôn bắt đầu tại trang 0.'],
  securityEn: ['Keep a finite `maxPages` and propagate the abort signal to the transport.'],
  securityVi: ['Giữ `maxPages` hữu hạn và truyền tín hiệu hủy tới transport.'],
  exampleIds: ['paging-zero', 'paging-one-based', 'typed-errors'],
});

const urlOptionsEntry = createEntry({
  symbol: 'UrlValidationOptions',
  kind: 'interface',
  pageId: 'api-validation-async',
  importPath: FNS_IMPORT,
  signature: 'interface UrlValidationOptions { protocols?: readonly string[]; allowRelative?: boolean; allowCredentials?: boolean; requireHost?: boolean; baseUrl?: string; }',
  en: 'Defines explicit URL syntax and policy checks.',
  vi: 'Định nghĩa kiểm tra cú pháp và chính sách URL tường minh.',
  parameters: [
    parameter('protocols', 'readonly string[]', 'Allowed protocols; values may include or omit the trailing colon.', 'Protocol được phép; giá trị có thể có hoặc không có dấu hai chấm cuối.', { optional: true, defaultValue: '["http:", "https:"]' }),
    parameter('allowRelative', 'boolean', 'Whether relative paths are accepted.', 'Có chấp nhận đường dẫn tương đối hay không.', { optional: true, defaultValue: 'false' }),
    parameter('allowCredentials', 'boolean', 'Whether embedded username/password credentials are accepted.', 'Có chấp nhận username/password nhúng hay không.', { optional: true, defaultValue: 'false' }),
    parameter('requireHost', 'boolean', 'Whether absolute URLs require a non-empty hostname.', 'URL tuyệt đối có bắt buộc hostname không rỗng hay không.', { optional: true, defaultValue: 'true' }),
    parameter('baseUrl', 'string', 'Parsing base used only for relative paths.', 'Base parser chỉ dùng cho đường dẫn tương đối.', { optional: true, defaultValue: '"http://localhost"' }),
  ],
  returnsEn: 'An options object consumed by `ValidationUtilities.isUrl`.',
  returnsVi: 'Object tùy chọn được `ValidationUtilities.isUrl` sử dụng.',
    runtimeEn: ['Protocol comparisons are normalized to lowercase and a trailing colon. Relative inputs must resolve to the configured base origin.'],
    runtimeVi: ['So sánh protocol được chuẩn hóa chữ thường và dấu hai chấm cuối. Input tương đối phải resolve về cùng origin với base đã cấu hình.'],
    securityEn: ['Cross-origin network-path/backslash references are rejected in relative mode. These options still do not implement SSRF protection, DNS/IP policy, redirect policy, or remote content validation.'],
    securityVi: ['Relative mode từ chối network-path/backslash trỏ sang origin khác. Các option này vẫn không triển khai chống SSRF, chính sách DNS/IP, redirect hay xác thực nội dung từ xa.'],
  exampleIds: ['numbers-validation'],
});

const uuidOptionsEntry = createEntry({
  symbol: 'UuidValidationOptions',
  kind: 'interface',
  pageId: 'api-validation-async',
  importPath: FNS_IMPORT,
  signature: 'interface UuidValidationOptions { version?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8; requireRfcVariant?: boolean; allowUppercase?: boolean; }',
  en: 'Configures generic UUID syntax validation.',
  vi: 'Cấu hình xác thực cú pháp UUID tổng quát.',
  parameters: [
    parameter('version', '1 | 2 | 3 | 4 | 5 | 6 | 7 | 8', 'Required UUID version nibble.', 'Nibble version UUID bắt buộc.', { optional: true, defaultValue: 'undefined' }),
    parameter('requireRfcVariant', 'boolean', 'Whether the variant nibble must be 8, 9, a, or b.', 'Có bắt buộc nibble variant là 8, 9, a hoặc b hay không.', { optional: true, defaultValue: 'false' }),
    parameter('allowUppercase', 'boolean', 'Whether uppercase hexadecimal is accepted.', 'Có chấp nhận hex chữ hoa hay không.', { optional: true, defaultValue: 'true' }),
  ],
  returnsEn: 'An options object consumed by `ValidationUtilities.isUuid`.',
  returnsVi: 'Object tùy chọn được `ValidationUtilities.isUuid` sử dụng.',
  runtimeEn: ['Without options, `isUuid` validates generic hyphenated hexadecimal shape and is not v4-specific.'],
  runtimeVi: ['Khi không có option, `isUuid` kiểm tra cấu trúc hex có dấu gạch nối tổng quát và không riêng v4.'],
  securityEn: ['UUID syntax and version bits do not prove secure generation, uniqueness, identity, or access rights.'],
  securityVi: ['Cú pháp và bit version UUID không chứng minh nguồn sinh an toàn, tính duy nhất, danh tính hay quyền truy cập.'],
  exampleIds: ['numbers-validation'],
});

const filterFunctionEntries = filterMemberSpecs.map(spec => entryFromMember('api-filter', spec));
const serializationFunctionEntries = [
  stableStringifySpec,
  canonicalStringifySpec,
  hashSpec,
  hash32Spec,
  sha256CanonicalSpec,
  sha256BlobSpec,
].map(spec => entryFromMember('api-object-utility-serialization', spec));
const utilityFunctionEntries = [
  fetchAllByPagingSpec,
  randomIdSpec,
  parseQueryParamsSpec,
  generateUuidSpec,
  getNestedValueSpec,
  isPlainObjectSpec,
  cloneSpec,
  mergeSpec,
  deepMergeSpec,
].map(spec => entryFromMember('api-object-utility-serialization', spec));

export const FUNCTION_B_API_ENTRIES = [
  filterNamespaceEntry,
  toEpochOptionsEntry,
  ...filterFunctionEntries,
  serializationOptionsEntry,
  stableOptionsEntry,
  canonicalOptionsEntry,
  ...serializationFunctionEntries,
  propertyPathOptionsEntry,
  plainRecordEntry,
  traversalOptionsEntry,
  pagingOptionsEntry,
  ...utilityFunctionEntries,
  objectNamespaceEntry,
  utilitiesNamespaceEntry,
  urlOptionsEntry,
  uuidOptionsEntry,
  validationNamespaceEntry,
] as const satisfies readonly ApiEntry[];

export const FUNCTION_B_DOCUMENTED_SYMBOLS = [
  'FilterUtilities',
  'ToEpochOptions',
  'match',
  'evaluate',
  'evaluateFilter',
  'validateFilter',
  'resolveData',
  'resolveRelativeDate',
  'toEpoch',
  'relativeDate',
  'isDateRelative',
  'SerializationOptions',
  'StableStringifyOptions',
  'CanonicalStringifyOptions',
  'stableStringify',
  'canonicalStringify',
  'hash',
  'hash32',
  'sha256Canonical',
  'sha256Blob',
  'PropertyPathOptions',
  'PlainRecord',
  'ObjectTraversalOptions',
  'FetchAllByPagingOptions',
  'fetchAllByPaging',
  'randomId',
  'parseQueryParams',
  'generateUuid',
  'getNestedValue',
  'isPlainObject',
  'clone',
  'merge',
  'deepMerge',
  'ObjectUtilities',
  'Utilities',
  'UrlValidationOptions',
  'UuidValidationOptions',
  'ValidationUtilities',
] as const;

export const FUNCTION_B_NAMESPACE_MEMBERS = {
  FilterUtilities: [
    'match',
    'evaluate',
    'evaluateFilter',
    'validateFilter',
    'resolveData',
    'resolveRelativeDate',
    'toEpoch',
    'relativeDate',
    'isDateRelative',
  ],
  ObjectUtilities: [
    'stableStringify',
    'canonicalStringify',
    'hash',
    'hash32',
    'sha256Canonical',
    'sha256Blob',
    'parseQueryParams',
    'getNestedValue',
    'isPlainObject',
    'clone',
    'merge',
    'deepMerge',
  ],
  Utilities: [
    'fetchAllByPaging',
    'randomId',
    'stableStringify',
    'canonicalStringify',
    'hash',
    'hash32',
    'sha256Canonical',
    'sha256Blob',
    'parseQueryParams',
    'generateUuid',
    'getNestedValue',
    'isPlainObject',
    'clone',
    'merge',
    'deepMerge',
  ],
  ValidationUtilities: [
    'validate',
    'isEmail',
    'isPhone',
    'isVnPhone',
    'isVnId',
    'isPassport',
    'isVnIdOrPassport',
    'isTime',
    'isUrl',
    'isDomain',
    'isIpv4',
    'isIpv6',
    'isImageUrl',
    'hasImageFileExtension',
    'isSlug',
    'isNumber',
    'isInteger',
    'isDecimal',
    'isPositiveNumber',
    'isFiniteNumber',
    'isNumericString',
    'parseFiniteNumber',
    'isUuid',
    'isUuidV4',
    'isCode16',
    'isCode32',
    'isHexColor',
    'isBase64',
    'isCode',
  ],
} as const;

export const FUNCTION_B_IMPORT_PATHS = {
  FilterUtilities: FNS_IMPORT,
  ToEpochOptions: FNS_IMPORT,
  match: FNS_IMPORT,
  evaluate: FNS_IMPORT,
  evaluateFilter: FNS_IMPORT,
  validateFilter: FNS_IMPORT,
  resolveData: FNS_IMPORT,
  resolveRelativeDate: FNS_IMPORT,
  toEpoch: FNS_IMPORT,
  relativeDate: FNS_IMPORT,
  isDateRelative: FNS_IMPORT,
  SerializationOptions: FNS_IMPORT,
  StableStringifyOptions: FNS_IMPORT,
  CanonicalStringifyOptions: FNS_IMPORT,
  stableStringify: FNS_IMPORT,
  canonicalStringify: FNS_IMPORT,
  hash: FNS_IMPORT,
  hash32: FNS_IMPORT,
  sha256Canonical: FNS_IMPORT,
  sha256Blob: FNS_IMPORT,
  PropertyPathOptions: FNS_IMPORT,
  PlainRecord: FNS_IMPORT,
  ObjectTraversalOptions: FNS_IMPORT,
  FetchAllByPagingOptions: FNS_IMPORT,
  fetchAllByPaging: FNS_IMPORT,
  randomId: FNS_IMPORT,
  parseQueryParams: FNS_IMPORT,
  generateUuid: FNS_IMPORT,
  getNestedValue: FNS_IMPORT,
  isPlainObject: FNS_IMPORT,
  clone: FNS_IMPORT,
  merge: FNS_IMPORT,
  deepMerge: FNS_IMPORT,
  ObjectUtilities: FNS_IMPORT,
  Utilities: FNS_IMPORT,
  UrlValidationOptions: FNS_IMPORT,
  UuidValidationOptions: FNS_IMPORT,
  ValidationUtilities: FNS_IMPORT,
} as const;
